

```{r,message=FALSE}
library(tidyverse)
library(lpirfs)
library(dplyr)
library(OrthoPanels)
library(jtools)
library(clipr)
```


```{r}
library(readr)

ln1 <- read_delim("ln1.csv", delim = ",", escape_double = FALSE, trim_ws = TRUE)
ia1 <- read_delim("ia1.csv", delim = ",", escape_double = FALSE, trim_ws = TRUE)
ia2 <- read_delim("ia2.csv", delim = ",", escape_double = FALSE, trim_ws = TRUE)
ia3 <- read_delim("ia3.csv", delim = ",", escape_double = FALSE, trim_ws = TRUE)
ia4 <- read_delim("ia4.csv", delim = ",", escape_double = FALSE, trim_ws = TRUE)
ia5 <- read_delim("ia5.csv", delim = ",", escape_double = FALSE, trim_ws = TRUE)
ia6 <- read_delim("ia6.csv", delim = ",", escape_double = FALSE, trim_ws = TRUE)

attach(ia1)
```

```{r}
# data_sample <- seq(1991, 2018)[which((seq(1991, 2018) %in% c(seq(1991,1992), seq(1993,2001), seq(2002,2003), seq(2008, 2009), seq(2011,2012) ,seq(2013))))]

data_sub = c(1991,1992,1993,2001,2002,2003,2008,2009,2011,2012,2013)
data_bo = c(1990,1994,1995,1996,1997,1998,1999,2000,2004,2005,2006,2007,2010,2014,2015,2016,2017,2018)

```


```{r}
# 
# pror1 = glm(ed_bb ~ Gini_net + gdp_gro+ Education_exp + employ_rate, data=bo1, family=binomial(link="probit"), na.action = na.exclude)
# summ(pror1)
# 
# pror1 = glm(he_bb ~ Gini_net + gdp_gro + Health_exp, data=bo1, family=binomial(link="probit"), na.action = na.exclude)
# summ(pror1)

# pror1 = glm(soc_bb ~ Gini_net + gdp_gro + lag(Soc_payable,1) + Gov_ex, data=bo1, family=binomial(link="probit"), na.action = na.exclude)
# summ(pror1)

# pror1 = glm(kind_bb ~ lag(Gini_net,1) + gdp_gro + Soc_kind + Gov_ex , data=b1, family=binomial(link="probit"), na.action = na.exclude)
# summ(pror1)

# pror1 = glm(prt_bb ~ lag(Gini_net,1) + lag(gdp_gro,1) + Property_taxes + Gov_ex , data=bo1 , family=binomial(link="probit"), na.action = na.exclude)
# summ(pror1)

# pror1 = glm(indt_bb ~ lag(Gini_net,1) + lag(gdp_gro,1) + ind_tx + Secondary_ed + Gov_ex , data=ia1 , family=binomial(link="probit"), na.action = na.exclude)
# summ(pror1)

bo1['pip_a'] = bo1$PIT*bo1$mrp_all
# 
pror1 = glm(pit_bb ~ lag(Gini_net,1) + lag(gdp_gro,1) + PIT + pip_a + Gov_ex , data=bo1 , family=binomial(link="probit"), na.action = na.exclude)
summ(pror1)#

# ln1['phat0'] = predict(pror, type = 'response')
bo1['phat0'] = predict(pror1, type = 'response')
bo1['invwt'] = bo1$pit_bb/bo1$phat0 + (1-bo1$pit_bb)/(1-bo1$phat0)

plot(bo1$phat0, bo1$pip_a)

```


```{r}
# invr1 = lm(Gini_net ~ dplyr::lag(Gini_netdm,1)+dplyr::lag(gdp_grodm,1) +Education_exp + employ_rate, weights = invwt, data = ia1) -- EDUCATION

# invr1 = lm(Gini_net ~ dplyr::lag(Gini_net,1) + dplyr::lag(Gini_netdm,1) + dplyr::lag(gdp_grodm,1) + (Health_exp) + Secondary_ed + employ_rate , weights = invwt, data = ia1) -- HEALTH

# invr1 = lm(Gini_net ~ dplyr::lag(Gini_netdm,1) + dplyr::lag(gdp_grodm,1) + dplyr::lag(gdp_grodm,2)+ dplyr::lag(Soc_payable,1)+dplyr::lag(Gov_ex,1)+Secondary_ed + employ_rate + dplyr::lag(Trade,1), weights = invwt, data = ia1) -- SOC PAYABLE

# invr1 = opm(Gini_net ~lag(gdp_gro,1) + Property_taxes + Gov_ex + Secondary_ed , data = ia1, index = c('idem','year'), n.samp = 10000, add.time.indicators = FALSE, weights=invwt)
# summary(invr1)

# invr1 = opm(Gini_net ~lag(gdp_gro,1) + ind_tx + Gov_ex + Secondary_ed , data = ia1, index = c('idem','year'), n.samp = 10000, add.time.indicators = FALSE, weights=invwt)
# summary(invr1) -- IND TAXES

# invr1 = opm(Gini_net ~lag(gdp_gro,1) + ia1$pip_a + mrp_all + PIT + Gov_ex + Secondary_ed , data = ia1, index = c('idem','year'), n.samp = 10000, add.time.indicators = FALSE, weights=invwt)
# summary(invr1) -- PIT

invr1 = opm(Gini_net ~ gdp_gro + Education_exp , data = b1, index = c('idem','year'), n.samp = 10000, add.time.indicators = FALSE, weights=invwt)
summary(invr1)

invr2 = opm(Gini_net ~ gdp_gro + Education_exp , data = b2, index = c('idem','year'), n.samp = 10000, add.time.indicators = FALSE, weights=invwt)
summary(invr2)

invr3 = opm(Gini_net ~ gdp_gro + Education_exp , data = b3, index = c('idem','year'), n.samp = 10000, add.time.indicators = FALSE, weights=invwt)
summary(invr3)

invr4 = opm(Gini_net ~ gdp_gro + Education_exp , data = b4, index = c('idem','year'), n.samp = 10000, add.time.indicators = FALSE, weights=invwt)
summary(invr4)

caterplot(invr1, 'beta', labels = c('growth','E'))

kind_beta = cbind.data.frame(invr1[["samples"]][["beta"]][,2], invr2[["samples"]][["beta"]][,2],
                           invr3[["samples"]][["beta"]][,2], invr4[["samples"]][["beta"]][,2],
                           invr5[["samples"]][["beta"]][,2], invr6[["samples"]][["beta"]][,2])

colnames(kind_beta) <- c("1", "2","3", "4","5", "6" ) 
```
```{r}
ia1   <- ia1 %>% group_by(idem) %>% mutate(ins_ed = 0.7*Education_exp + rnorm(length(Education_exp), 0, sd(na.omit(Education_exp))/10)) %>% ungroup()
```

```{r}
df_1 <- na.omit(ia1)

#Remove rows with NA's using complete.cases
df_2 <- ia1[complete.cases(ia1), ] 

#Remove rows with NA's using rowSums()
df_3 <- ia1[rowSums(is.na(ia1)) == 0, ] 
```


```{r}
ponl <-  lp_nl_panel(data_set          = df_1,
                               data_sample       = data_bo,
                               cumul_mult        = TRUE,
                               shock             = "Education_exp",
                               endog_data = "Gini_net",
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                               # instrum =   c('ins_ed'), iv_reg = TRUE,
                               robust_cov   = "vcovSCC", 
                               # robust_type="HC0", robust_cluster= "vcovHC",   
                            c_exog_data   = c('Gov_ex'),
                              switching = 'lgdpg', 
                               lags_exog_data = 2,
                                lag_switching     = TRUE,
                               use_hp            = TRUE,
                               lambda            = 6.25,
                               gamma             = 10,
                               l_exog_data    =c('Gov_ex'),
                               c_fd_exog_data = c('GDP_tren'),
                               l_fd_exog_data = c('GDP_tren', 'Secondary_ed'),
                               # l_fd_exog_data    = c('employ_rate'),
                               lags_fd_exog_data = 2,  confint  = 1.67, hor = 5)

```

```{r}
nl_plots <- plot_nl(ponl)

 # Compare states
library(ggpubr)
library(gridExtra)
combine_plots <- list(nl_plots$gg_s1[[1]], nl_plots$gg_s2[[1]])
marrangeGrob(combine_plots, nrow = 1, ncol = 2, top = NULL)
```


```{r}

po1 <-  lp_lin_panel(data_set          = ia1,
                               data_sample       = data_bo,
                               cumul_mult        = TRUE,
                               shock             = "Education_exp",
                               endog_data = "Gini_net",
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                               # instrum =   c('ins_ed'), iv_reg = TRUE,
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",                                                          c_exog_data   = c('Gov_ex'),
                               lags_exog_data = 2,
                               l_exog_data    =c('Gov_ex'),
                               c_fd_exog_data = c('GDP_tren'),
                               l_fd_exog_data = c('GDP_tren', 'Secondary_ed'),
                               # l_fd_exog_data    = c('employ_rate'),
                               lags_fd_exog_data = 2,  confint  = 1.67, hor = 5)

plot_lin(po1)

lpo1 = data.frame(x =1:5,estm=c(po1[["irf_panel_mean"]]),low=c(po1[["irf_panel_low"]]),up=c(po1[["irf_panel_up"]]))

lto = rbind(po1[["reg_summaries"]][[1]][1,], po1[["reg_summaries"]][[2]][1,],
               po1[["reg_summaries"]][[3]][1,], po1[["reg_summaries"]][[4]][1,],
               po1[["reg_summaries"]][[5]][1,])

write_clip(lto)


po2 <-  lp_lin_panel(data_set          = ia1,
                               data_sample       = data_bo,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "Soc_payable",
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('Gov_ex'),
                               lags_exog_data = 2,
                               l_exog_data    = c('Gov_ex'),
                               c_fd_exog_data = c('GDP_tren', 'Secondary_ed'),
                               l_fd_exog_data = c('GDP_tren', 'Secondary_ed','employ_rate'),
                               # l_fd_exog_data    = c('employ_rate'),
                               lags_fd_exog_data = 2,  confint  = 1.67, hor = 5)

lpo2 = data.frame(x =1:5,estm=c(po2[["irf_panel_mean"]]),low=c(po2[["irf_panel_low"]]),up=c(po2[["irf_panel_up"]]))

lto2 = rbind(po2[["reg_summaries"]][[1]][1,], po2[["reg_summaries"]][[2]][1,],
             po2[["reg_summaries"]][[3]][1,], po2[["reg_summaries"]][[4]][1,],
             po2[["reg_summaries"]][[5]][1,])

write_clip(lto2)

po3 <-  lp_lin_panel(data_set          = ia1,
                               data_sample       = data_bo,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "Soc_kind",
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('Gov_ex'),
                               lags_exog_data = 2,
                               l_exog_data    = c('Gov_ex'),
                               c_fd_exog_data = c('Secondary_ed','GDP_tren'),
                               l_fd_exog_data = c('Secondary_ed','GDP_tren'),
                              lags_fd_exog_data = 2, confint = 1.67, hor = 5)

lpo3 = data.frame(x =1:5,estm=c(po3[["irf_panel_mean"]]),low=c(po3[["irf_panel_low"]]),up=c(po3[["irf_panel_up"]]))

lto3 = rbind(po3[["reg_summaries"]][[1]][1,], po3[["reg_summaries"]][[2]][1,],
           po3[["reg_summaries"]][[3]][1,], po3[["reg_summaries"]][[4]][1,],
           po3[["reg_summaries"]][[5]][1,])

write_clip(lto3)

po4 <-  lp_lin_panel(data_set          = ia1,
                               data_sample       = data_bo,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = 'Property_taxes',
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('Gov_ex'),
                               lags_exog_data = 2,
                               l_exog_data    =c('Gov_ex'),
                               c_fd_exog_data = c('GDP_tren', 'employ_rate'),
                               l_fd_exog_data = c('GDP_tren', 'employ_rate'),
                               lags_fd_exog_data = 2,  confint  = 1.67, hor = 5)

lpo4 = data.frame(x =1:5,estm=c(po4[["irf_panel_mean"]]),low=c(po4[["irf_panel_low"]]),up=c(po4[["irf_panel_up"]]))

lto4 = rbind(po4[["reg_summaries"]][[1]][1,], po4[["reg_summaries"]][[2]][1,],
           po4[["reg_summaries"]][[3]][1,], po4[["reg_summaries"]][[4]][1,],
           po4[["reg_summaries"]][[5]][1,])

write_clip(lto4)

po5 <-  lp_lin_panel(data_set          = ia1,
                               data_sample       = data_bo,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = 'pip_a',
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('Gov_ex'),
                               lags_exog_data = 2,
                               l_exog_data    =c('GDP_tren','employ_rate'),
                               l_fd_exog_data = c('GDP_tren','employ_rate','mrp_all'),
                               lags_fd_exog_data = 2,  confint  = 1.67, hor = 5)

lpo5 = data.frame(x =1:5,estm=c(po5[["irf_panel_mean"]]),low=c(po5[["irf_panel_low"]]),up=c(po5[["irf_panel_up"]]))

lto5 = rbind(po5[["reg_summaries"]][[1]][1,], po5[["reg_summaries"]][[2]][1,],
           po5[["reg_summaries"]][[3]][1,], po5[["reg_summaries"]][[4]][1,],
           po5[["reg_summaries"]][[5]][1,])


write_clip(lto5)

```

```{r}
po1b <-  lp_lin_panel(data_set          = ia1,
                               data_sample       = data_sub,
                               cumul_mult        = TRUE,
                               shock             = "Education_exp",
                               endog_data = "Gini_net",
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",                                                          c_exog_data   = c('Gov_ex'),
                               lags_exog_data = 2,
                               l_exog_data    =c('Gov_ex'),
                               c_fd_exog_data = c('GDP_tren'),
                               l_fd_exog_data = c('GDP_tren', 'Secondary_ed'),
                               # l_fd_exog_data    = c('employ_rate'),
                               lags_fd_exog_data = 2,  confint  = 1.67, hor = 5)

lpo1b = data.frame(x =1:5,estm=c(po1b[["irf_panel_mean"]]),low=c(po1b[["irf_panel_low"]]),up=c(po1b[["irf_panel_up"]]))

ltob = rbind(po1b[["reg_summaries"]][[1]][1,], po1b[["reg_summaries"]][[2]][1,],
               po1b[["reg_summaries"]][[3]][1,], po1b[["reg_summaries"]][[4]][1,],
               po1b[["reg_summaries"]][[5]][1,])

write_clip(ltob)


po2b <-  lp_lin_panel(data_set          = ia1,
                               data_sample       = data_sub,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = FALSE,
                               shock             = "Soc_payable",
                               diff_shock        = FALSE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('Gov_ex'),
                               lags_exog_data = 2,
                               l_exog_data    = c('Gov_ex'),
                               c_fd_exog_data = c('GDP_tren', 'Secondary_ed'),
                               l_fd_exog_data = c('GDP_tren', 'Secondary_ed','employ_rate'),
                               # l_fd_exog_data    = c('employ_rate'),
                               lags_fd_exog_data = 2,  confint  = 1.67, hor = 5)



lpo2b = data.frame(x =1:5,estm=c(po2b[["irf_panel_mean"]]),low=c(po2b[["irf_panel_low"]]),up=c(po2b[["irf_panel_up"]]))

lto2b = rbind(po2b[["reg_summaries"]][[1]][1,], po2b[["reg_summaries"]][[2]][1,],
             po2b[["reg_summaries"]][[3]][1,], po2b[["reg_summaries"]][[4]][1,],
             po2b[["reg_summaries"]][[5]][1,])

write_clip(lto2b)

po3b <-  lp_lin_panel(data_set          = ia1,
                             data_sample       = data_sub,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = FALSE,
                               shock             = "Soc_kind",
                               diff_shock        = FALSE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('Gov_ex'),
                               lags_exog_data = 2,
                               l_exog_data    = c('Gov_ex'),
                               c_fd_exog_data = c('Secondary_ed','GDP_tren'),
                               l_fd_exog_data = c('Secondary_ed','GDP_tren'),
                               lags_fd_exog_data = 2, confint = 1.67, hor = 5)

lpo3b = data.frame(x =1:5,estm=c(po3b[["irf_panel_mean"]]),low=c(po3b[["irf_panel_low"]]),up=c(po3b[["irf_panel_up"]]))

lt3b = rbind(po3b[["reg_summaries"]][[1]][1,], po3b[["reg_summaries"]][[2]][1,],
           po3b[["reg_summaries"]][[3]][1,], po3b[["reg_summaries"]][[4]][1,],
           po3b[["reg_summaries"]][[5]][1,])

write_clip(lt3b)

po4b <-  lp_lin_panel(data_set          = ia1,
                             data_sample       = data_sub,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = FALSE,
                               shock             = 'Property_taxes',
                               diff_shock        = FALSE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('Gov_ex'),
                               lags_exog_data = 2,
                               l_exog_data    =c('Gov_ex'),
                               c_fd_exog_data = c('GDP_tren', 'employ_rate'),
                               l_fd_exog_data = c('GDP_tren', 'employ_rate'),
                               lags_fd_exog_data = 2,  confint  = 1.67, hor = 5)

lpo4b = data.frame(x =1:5,estm=c(po4b[["irf_panel_mean"]]),low=c(po4b[["irf_panel_low"]]),up=c(po4b[["irf_panel_up"]]))

lto4b = rbind(po4b[["reg_summaries"]][[1]][1,], po4b[["reg_summaries"]][[2]][1,],
           po4b[["reg_summaries"]][[3]][1,], po4b[["reg_summaries"]][[4]][1,],
           po4b[["reg_summaries"]][[5]][1,])

write_clip(lto4b)

po5b <-  lp_lin_panel(data_set          = ia1,
                             data_sample       = data_sub,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = FALSE,
                               shock             = 'pip_a',
                               diff_shock        = FALSE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('Gov_ex'),
                               lags_exog_data = 2,
                               l_exog_data    =c('GDP_tren','employ_rate'),
                               l_fd_exog_data = c('GDP_tren','employ_rate','mrp_all'),
                               lags_fd_exog_data = 2,  confint  = 1.67, hor = 5)

lpo5b = data.frame(x =1:5,estm=c(po5b[["irf_panel_mean"]]),low=c(po5b[["irf_panel_low"]]),up=c(po5b[["irf_panel_up"]]))

lto5b = rbind(po5b[["reg_summaries"]][[1]][1,], po5b[["reg_summaries"]][[2]][1,],
           po5b[["reg_summaries"]][[3]][1,], po5b[["reg_summaries"]][[4]][1,],
           po5b[["reg_summaries"]][[5]][1,])


write_clip(lto5b)
```


```{r}
cfi <- function(hori, me, low, up, color, tit) {
  plot(hori, me, ylim = c(y2,y1), type = "l", main = tit, xlab = "horizon", ylab= '')
  polygon(c(hori,rev(hori)),c(low,rev(up)), col = adjustcolor("gray70" ,alpha.f=0.4) , border = NA)
  lines(hori, me, lwd = 2, col = color)
  lines(hori, up, lty = 1, col="gray50")
  lines(hori, low, lty = 1, col="gray50")
  abline(h =0, col='black', lty = 2 )
}

```



```{r}
## "Education_exp"
y1 = max(lpo1$up) + 0.005
y2 = min(lpo1$low) - 0.005

par(mfrow=c(1,2))

cfi(lpo1$x, lpo1$estm,lpo1$low,lpo1$up, 'royalblue1', 'Boom')

y1 = max(lpo1b$up) + 0.005
y2 = min(lpo1b$low) - 0.005

cfi(lpo1b$x,lpo1b$estm,lpo1b$low,lpo1b$up, 'sienna2', 'Bust')
```


```{r}
## "Payable Transfers"
y1 = max(lpo2$up) + 0.05
y2 = min(lpo2$low) - 0.05

par(mfrow=c(1,2))

cfi(lpo2$x, lpo2$estm,lpo2$low,lpo2$up, 'blue', 'Boom')

y1 = max(lpo2b$up) + 0.05
y2 = min(lpo2b$low) - 0.05

cfi(lpo2b$x,lpo2b$estm,lpo2b$low,lpo2b$up, 'firebrick', 'Bust')
```


```{r}
## "Payable Transfers"
y1 = max(lpo3$up) + 0.05
y2 = min(lpo3b$low) - 0.05

par(mfrow=c(1,2))

cfi(lpo3$x, lpo3$estm,lpo3$low,lpo3$up, 'blue', 'Boom')

y1 = max(lpo2b$up) + 0.05
y2 = min(lpo2b$low) - 0.05

cfi(lpo3b$x,lpo3b$estm,lpo3b$low,lpo3b$up, 'firebrick', 'Bust')
```


```{r}
## "Property taxes"
y1 = max(lpo4$up) + 0.005
y2 = min(lpo4$low) - 0.005

par(mfrow=c(1,2))

cfi(lpo4$x, lpo4$estm,lpo4$low,lpo4$up, 'blue', 'Boom')

y1 = max(lpo4b$up) + 0.005
y2 = min(lpo4b$low) - 0.005

cfi(lpo4b$x,lpo4b$estm,lpo4b$low,lpo4b$up, 'firebrick', 'Bust')
```


```{r}
## "PIT"
y1 = max(lpo5$up) + 0.005
y2 = min(lpo5$low) - 0.005

par(mfrow=c(1,2))

cfi(lpo5$x, lpo5$estm,lpo5$low,lpo5$up, 'blue', 'Boom')

y1 = max(lpo5b$up) + 0.005
y2 = min(lpo5b$low) - 0.005

cfi(lpo5b$x,lpo5b$estm,lpo5b$low,lpo5b$up, 'firebrick', 'Bust')
```



```{r}
write.csv(b1,"b1.csv",row.names = FALSE)
write.csv(b2,"b2.csv",row.names = FALSE)
write.csv(b3,"b3.csv",row.names = FALSE)
write.csv(b4,"b4.csv",row.names = FALSE)

write.csv(bo1,"bo1.csv",row.names = FALSE)
write.csv(bo2,"bo2.csv",row.names = FALSE)
write.csv(bo3,"bo3.csv",row.names = FALSE)
write.csv(bo4,"bo4.csv",row.names = FALSE)
write.csv(bo5,"bo5.csv",row.names = FALSE)
write.csv(bo6,"bo6.csv",row.names = FALSE)
```

```{r}
GYsc            <- mean(exp(ia1$Gini_net)/exp(ia1$Education_exp), na.rm = TRUE)

multiplier_mean <- po1$irf_panel_mean*GYsc
multiplier_up   <- po1$irf_panel_up*GYsc
multiplier_low  <- po1$irf_panel_low*GYsc

results_lin_iv  <- list(irf_lin_mean  = multiplier_mean,
                        irf_lin_up    = multiplier_up,
                        irf_lin_low   = multiplier_low,
                        specs         = po1$specs)
x =1:5
# Make new plots 
plot_lin(results_lin_iv)

y1 = max(results_lin_iv$irf_lin_up) + 0.005
y2 = min(results_lin_iv$irf_lin_low) - 0.005

par(mfrow=c(1,2))

cfi(x , results_lin_iv$irf_lin_mean,results_lin_iv$irf_lin_low,results_lin_iv$irf_lin_up, 'blue', 'Boom')


```
```{r}
endog_data <- interest_rules_var_data
```


