---
title: "Clean data"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r, message = off}
library(tidyverse)
library(readxl)
library(lmtest)

#library(psych)
```


```{r}
ine <- read_excel("F:/INEQUALITY/2020/FINAL 04.xlsx", sheet = "log (2)")

# ine <-  as.data.frame(ine)
# ine2 <- drop_na(ine)

#inef <- drop_na(ineD)
```

```{r}
# ine2$year <- NULL
# ine2$idem <- NULL
# ine2$debt_g <- NULL
# se va el grupo de deuda

inst <- ine[c(1:667), c(1:2,54:66)]
base <- ine[c(1:667), c(1:53)]
base <- subset(base, select=-c(pop, GDP_curr, GDP_con))
ineq <- ine[c(1:667), c(74:90)]
saving_tic <- ine[c(1:667), c(67:73)]

```

```{r}
skewedVars<- NA
library(moments) # for skewness()
for(i in names(ine)){
       skewVal <- skewness(ine[,i])
       print(paste(i, skewVal, sep = ": "))
       if(abs(skewVal) > 1.15){
         skewedVars <- c(skewedVars, i)
       }
}

# solo tomar td_fe
# inst en growth y graficos aparte
```

```{r}
library(purrr)
library(tidyr)
library(ggplot2)
library(ggthemes)

rest %>% keep(is.numeric) %>% 
  gather() %>% ggplot(aes(value)) +
    facet_wrap(~ key , scales = "free") +
    geom_histogram(colour="blue") + theme_wsj(base_size = 8)


# Boxplots

inst %>% keep(is.numeric) %>% 
  gather() %>% ggplot(aes(value)) +
    facet_wrap(~ key , scales = "free") +
    geom_histogram(colour="blue", fill='gray') + theme_wsj(base_size = 8)

saving_tic %>% keep(is.numeric) %>% 
  gather() %>% ggplot(aes(value)) +
    facet_wrap(~ key , scales = "free") +
    geom_histogram(colour="blue", fill='gray') + theme_wsj(base_size = 8)

ineq %>% keep(is.numeric) %>% 
  gather() %>% ggplot(aes(value)) +
    facet_wrap(~ key , scales = "free") +
    geom_boxplot(colour="blue", fill='gray') + theme_wsj(base_size = 8)

```

limpiar: gro_GDPpc

```{r}
library(corrplot)

# ine2$year <- NULL
ine2 <- subset(ine, select=-c(pop, GDP_curr, GDP_con))

base %>% keep(is.numeric) -> base_cor
inst %>% keep(is.numeric) -> inst_cor

# adding Gini_net
inst_cor$Gini_net = ine$Gini_net
saving_tic$Gini_net = ine$Gini_net
ineq$Gini_net = ine$Gini_net

corr_b <- cor(na.omit(base_cor))
corr_ins <- cor(na.omit(inst_cor))
corr_sa <- cor(na.omit(saving_tic))
corr_ineq <- cor(na.omit(ineq))

row_indic <- apply(corr_b, 1, function(x) sum(x > 0.60 | x < -0.60) > 1)
row_indic2 <- apply(corr_ins, 1, function(x) sum(x > 0.40 | x < -0.40) > 1)
row_indic3 <- apply(corr_sa, 1, function(x) sum(x > 0.50 | x < -0.50) > 1)
row_indic4 <- apply(corr_ineq, 1, function(x) sum(x > 0.75 | x < -0.75) > 1)

corr <- corr_b[row_indic ,row_indic]
corr2 <- corr_ins[row_indic2 ,row_indic2]
corr3 <- corr_sa[row_indic3 ,row_indic3]
corr4 <- corr_ineq[row_indic4 ,row_indic4]

corrplot(corr, method="square", diag = F,order = 'hclust', tl.cex = .8)
corrplot(corr2, method="ellipse", diag = F,order = 'hclust', tl.cex = .8)
corrplot(corr3, method="ellipse", diag = F,order = 'hclust', tl.cex = .8)
corrplot(corr4, method="ellipse", diag = F,order = 'hclust', tl.cex = .8)
```
le_female, net_len_w/i, soc_payable, gov_ex, soc_prot, td_female, tertiary_ed, voice, ruleoflaw, goveff, soc_proc_ex_pen, trade, 

```{r}
plotHist <- function(data_in, i) {
    data <- data.frame(x=data_in[[i]])
    p <- ggplot(data=data, aes(x=factor(x))) + stat_count() + xlab(colnames(data_in)[i]) + theme_grey() + 
   theme(axis.text.x = element_text(angle = 90, hjust =1))
    return (p)
}
```

```{r}
library(gridExtra)
doPlots <- function(data_in, fun, ii, ncol=2) {
    pp <- list()
    for (i in ii) {
        p <- fun(data_in=data_in, i=i)
        pp <- c(pp, list(p))
    }
    do.call("grid.arrange", c(pp, ncol=ncol))
}
```

```{r}
plotDen <- function(data_in, i){
    data <- data.frame(x=data_in[[i]], y = data_in$Gini_net)
    p <- ggplot(data= data) + geom_bar(aes(x = x), stat = 'density', size = 1, alpha = 0.7) + xlab(paste0((colnames(data_in)[i]), '\n', 'Skewness:',
round(skewness(data_in[[i]], na.rm = T), 2))) 
return(p)
    }
```

```{r}
doPlots(ine2, fun = plotDen, ii = 11:19, ncol = 3)
```

```{r}
plotCorr <- function(data_in, i){
data <- data.frame(x = data_in[[i]], y= data_in$Gini_net)
p <- ggplot(data, aes(x = x, y = y)) + geom_point(shape = 1, na.rm = T) +  geom_smooth(method = lm ) + xlab(paste0(colnames(data_in)[i], 
  '\n', 'R-Squared: ', round(cor(data_in[[i]], data$y, 
 use = 'complete.obs'), 2))) 
 return(suppressWarnings(p))
}
```

```{r}
highcorr_b <- c(names(corr_b[,'Gini_net'])[which(corr_b[,'Gini_net'] > 0.05)],
    names(corr_b[,'Gini_net'])[which(corr_b[,'Gini_net'] < -0.05)])

highcorr_ins <- c(names(corr_ins[,'Gini_net'])[which(corr_ins[,'Gini_net'] > 0.15)],
    names(corr_ins[,'Gini_net'])[which(corr_ins[,'Gini_net'] < -0.15)])

highcorr_ineq <- c(names(corr_ineq[,'Gini_net'])[which(corr_ineq[,'Gini_net'] > 0.75)],
    names(corr_ineq[,'Gini_net'])[which(corr_ineq[,'Gini_net'] < -0.75)])

highcorr_sa <- c(names(corr_sa[,'Gini_net'])[which(corr_sa[,'Gini_net'] > 0.15)],
    names(corr_sa[,'Gini_net'])[which(corr_sa[,'Gini_net'] < -0.15)])

data_corr <- ine2[, highcorr_b]
doPlots(data_corr, fun = plotCorr, ii = c(2,10,7:9, 13))

data_corr_ins <- ine2[, highcorr_ins]
doPlots(data_corr_ins, fun = plotCorr, ii = c(1,4:8))

data_corr_sa <- ine2[, highcorr_sa]
doPlots(data_corr_sa, fun = plotCorr, ii = c(2:6))

```

```{r}
a <- c(names(data_corr))
a = a[a!= 'year'] 
b <- c(names(data_corr_ins)) 
b = b[b!= 'Gini_net'] 
c = c(names(data_corr_sa))
c = c[c!= 'Gini_net'] 

da = c(a,b,c)
final <- ine %>% select(1:3)
final <- cbind(final,ine[, da])
```

```{r}
library("xlsx")

write.xlsx(final, file = "final.xlsx", sheetName="DAN", col.names = T)
```


https://rpubs.com/nischalthapa/267813


```{r}
# PANEL GROWTH RATE

library(tidyverse)  # Love dplyr!

my.panel.df <- ine%>%
  arrange(idem, year) %>%  # Sort by firm and then by year
  group_by(idem) %>%  # Tell dplyr to go within each firm
  mutate(sg.diff = G99 - lag(G99), 
         sgr = (100*(sg.diff/lag(G99))),
         dgr.diff = G99 - lag(AVGTOP), 
         dgr = (100*(dgr.diff/lag(AVGTOP)))) 
```


Data transformation negative logs

https://discuss.analyticsvidhya.com/t/methods-to-deal-with-zero-values-while-performing-log-transformation-of-variable/2431/8

https://blogs.sas.com/content/iml/2011/04/27/log-transformations-how-to-handle-negative-data-values.html

le_female, net_len_w/i, soc_payable, gov_ex, soc_prot, td_female, tertiary_ed, voice, ruleoflaw, goveff, soc_proc_ex_pen, trade, 


### FEATURE SELECTION

https://www.machinelearningplus.com/machine-learning/feature-selection/

```{r}
library(readxl)

final <- read_excel("final.xlsx")

final$...1 <- NULL
final$...2 <- NULL
```

```{r}
final %>% keep(is.numeric) -> db
db %>% keep(is.numeric) -> db

db %>% dplyr::select(where(is.numeric)) -> db2
db2 = na.omit(db2)

db3 = select_if(final, is.numeric)
db2$year <- NULL
db2$Quantiles <-NULL
```

```{r}
base.mod <- lm(Gini_net ~ Wages , data=db2)  
all.mod <- lm(Gini_net ~ . , data=db2) 

stepMod <- step(base.mod, scope = list(lower = base.mod, upper = all.mod), direction = "both", trace = 0, steps = 1000)

shortlistedVars <- names(unlist(stepMod[[1]]))
shortlistedVars <- shortlistedVars[!shortlistedVars %in% "(Intercept)"] # remove intercept

print(shortlistedVars)
```
```{r}
# install.packages('relaimpo')
library(relaimpo)

model_formula = Gini_net ~ gro_pop + Trade  + arp_mid + mrp_all + Family

# 20 vAR
md = Gini_net ~ Wages + Corporate_ta + Unempl_rate + Net_len_wi + instdepth + Secondary_ed + Gov_debt + ins_effic + Savings_percapit + Deficit + Social_prot + Soc_kind  + employ_rate + Tertiary_ed + TOT + property_tx + GDP_pc + HICP + Health_exp +  Gov_ex + regqua 

# 20 vAR
md2 = Gini_net ~ ICT + Education_exp + pr_im_tx + Deficit + insaccess + ruleoflaw + ins_effic + sav_gdp + Net_mig + Social_prot_ex_pen + ind_tx + Soc_payable + voice  + gro_pop + Trade  + arp_mid + mrp_all + Family + re_1mill

mdf = Gini_net ~ Social_prot + Secondary_ed + Savings_percapit +Gov_ex + Soc_kind + Wages + employ_rate +
GDP_pc + TOT + Corporate_ta + Social_prot_ex_pen + insaccess+ arp_mid + Trade + sav_gdp +
 re_1mill + rd_gdp + Net_mig + ICT + Family + ind_tx

mdb = Gini_net ~ Tertiary_ed +  Health_exp+ property_tx +  Unempl_rate + regqua + Gov_debt +     Net_len_wi +  instdepth  +  HICP + ruleoflaw +voice + pr_im_tx + Soc_payable +  mrp_all  +  Education_exp + gro_pop + Deficit + ins_effic

lmMod <- lm(mdb, data=db2)

relImportance <- calc.relimp(lmMod, type = "lmg", rela = F)
relImportance2 <- calc.relimp(lmMod, type = "lmg", rela = F)
relImportancef <- calc.relimp(lmMod, type = "lmg", rela = F)
relImportanceb <- calc.relimp(lmMod, type = "lmg", rela = F)

cat('Relative Importances: \n')
sort(round(relImportancef$lmg, 3), decreasing=TRUE)

# bootsub <- boot.relimp(lmMod, data=db2, b = 1000, type = 'lmg', rank = TRUE, diff = TRUE)
# 
# plot(booteval.relimp(bootsub, level=.95))


library("xlsx")

write.xlsx(db2, file = "db.xlsx", sheetName="DAN", col.names = T)
```

```{r}
i = i[i!= 'Gini_net'] 
i1 = paste(i, collapse='+')

md2 = Gini_net ~ Gov_debt+Unempl_rate+Wages+HICP+property_tx+Net_mig+Gini_market+Net_len_wi+le_male+le_female+Deciles+Health_exp+Education_exp+Social_prot_ex_pen+Social_prot+Family+Unemp_tra+Corporate_ta+ind_tx+`gro%pop`+Trade+TOT+GDP_pc+Secondary_ed+Tertiary_ed+td_male+td_female+leavers+Gov_ex+Deficit+Soc_payable+Soc_kind+employ_rate+arp_mid+mrp_all+insaccess+goveff+regqua+ruleoflaw+voice+instdepth+ins_effic+`R&D%GDP\r\n`+`Researchers_(1mill_Pop)\r\n`+`Savings % GDP`+Savings_percapit+ICT

pform <- pFormula(Gini_net ~ Gov_debt+Unempl_rate+Wages+HICP+property_tx+Net_mig+Gini_market+Net_len_wi+le_male+le_female+Deciles+Health_exp+Education_exp+Social_prot_ex_pen+Social_prot+Family+Unemp_tra+Corporate_ta+ind_tx+Trade+TOT+GDP_pc+Secondary_ed+Tertiary_ed+td_male+td_female+leavers+Gov_ex+Deficit+Soc_payable+Soc_kind+employ_rate+arp_mid+mrp_all+insaccess+goveff+regqua+ruleoflaw+voice+instdepth+ins_effic+Savings_percapit+ICT)

mf <- model.frame(pform, data=pdata.frame(db2))

# no linear dependent columns in original data/pooling model
modmat_pool <- model.matrix(pform, data = mf, model="pooling")
detect.lindep(modmat_pool)
mod_pool <- plm(pform, data = db2, model = "pooling")
(mod_pool)

modmat_FE <- model.matrix(pform, data = mf, model="within")
detect.lindep(modmat_FE)
mod_FE <- plm(pform, data = db2, model = "within")
detect.lindep(mod_FE)
alias(mod_FE)
```




```{r}
library(caret)
sa_ctrl <- safsControl(functions = rfSA,
                        method = "repeatedcv",
                        repeats = 3,
                        improve = 5)

sa_obj <- safs(x=db2[, -c(7,10,11)], 
               y=db2$Gini_net,
               safsControl = sa_ctrl)

sa_obj

print(sa_obj$optVariables)
```

```{r}
library(randomForest)
library(DALEX)

rf_mod_selected <- randomForest(Gini_net ~ ICT + Education_exp + db2$`prod&imp_tx` + Deficit + insaccess + ruleoflaw + ins_effic + db2$`Savings % GDP` + Net_mig + Social_prot_ex_pen + ind_tx + Soc_payable + voice  + db2$`gro%pop` + Trade  + arp_mid + mrp_all + Family + Gov_debt + db2$`Researchers_(1mill_Pop)\r\r\n` + db2$`R&D%GDP\r\r\n`, data=db2, ntree=500)

selected <- randomForest(Gini_net ~ Savings_percapit +Soc_kind+Secondary_ed+employ_rate+GDP_pc+Social_prot+Wages+property_tx+ Gov_ex+Tertiary_ed+Gov_debt+
  Social_prot_ex_pen+Trade+insaccess+Net_mig+Education_exp+voice+arp_mid+ruleoflaw+ind_tx+ICT+mrp_all,
  data=db2, ntree=500)
  
rf_mod

selected

explainer_ranger <- explain(selected, data = db2[,-c(7,10,11)], y= db2$Gini_net, label = "Higher sample")

explained_rf <- model_parts(explainer_ranger, type = "variable_importance")

plot(explained_rf, max_vars=15, bar_width=6)

explained_rf
```

```{r}
library(Boruta)

boruta_1 <- Boruta(md , data = db2, doTrace = 2)

boruta_2 <- Boruta(md2 , data = db2, doTrace = 2)

print(boruta_1)

plot(boruta_1, xlab = "", xaxt = "n")
k <-lapply(1:ncol(boruta_1$ImpHistory),function(i)
  boruta_1$ImpHistory[is.finite(boruta_1$ImpHistory[,i]),i])
names(k) <- colnames(boruta_1$ImpHistory)
Labels <- sort(sapply(k,median))
axis(side = 1,las=2,labels = names(Labels), at = 1:ncol(boruta_1$ImpHistory), cex.axis = 0.7)
```

```{r}
attStats(boruta_1)

```


```{r}
print(boruta_2)

plot(boruta_2, xlab = "", xaxt = "n")
k <-lapply(1:ncol(boruta_2$ImpHistory),function(i)
  boruta_2$ImpHistory[is.finite(boruta_2$ImpHistory[,i]),i])
names(k) <- colnames(boruta_2$ImpHistory)
Labels <- sort(sapply(k,median))
axis(side = 1,las=2,labels = names(Labels), at = 1:ncol(boruta_2$ImpHistory), cex.axis = 0.7)
```


```{r}
library(caret)
control <- rfeControl(functions=lmFuncs, method="cv", number=10 )
x = db2[,-c(7,10,11)]
y = as.matrix(db2[7])
rfe <- rfe(x, y, rfeControl=control)
print(rfe, top=20)
plot(rfe, type=c("g", "o"), cex = 1.0)
predictors(rfe)
head(rfe$resample,20)

```



