---
title: "clean"
output: html_document
date: "2023-10-15"
---

```{r,message=FALSE}
library(tidyverse)
library(readxl)
library(mFilter)
library(datawizard)
```


```{r}
Clean_DB <- read_excel("C:/Users/canut/Desktop/Clean DB.xlsx")
```

```{r}
name = colnames(Clean_DB)

hp <- as.data.frame(Clean_DB %>%
      arrange(serie) %>%  
      group_by(idem) %>%      
      mutate_at(vars(name),~ ifelse(is.na(.x), mean(.x, na.rm = TRUE), .x)))

temp = as.data.frame(hp %>% select(all_of(name)))
```


```{r}
fh <- temp %>% arrange(idem, year) %>% group_by(idem) %>% 
         filter(!is.na(Gini_net)) %>% 
         mutate(gi_trend = mFilter::hpfilter(Gini_net, type = "lambda", freq = 6.25)$trend,
         ed_trend = mFilter::hpfilter(Education_exp, type = "lambda", freq = 6.25)$trend,
         he_trend = mFilter::hpfilter(Health_exp, type = "lambda", freq = 6.25)$trend,
         soc_trend = mFilter::hpfilter(Soc_payable, type = "lambda", freq = 6.25)$trend,
         gov_trend = mFilter::hpfilter(Gov_ex, type = "lambda", freq = 6.25)$trend,
         kind_trend = mFilter::hpfilter(Soc_kind, type = "lambda", freq = 6.25)$trend,
         gdp_trend = mFilter::hpfilter(gdp_gro, type = "lambda", freq = 6.25)$trend,
         def_trend = mFilter::hpfilter(Deficit, type = "lambda", freq = 6.25)$trend,
         sav_trend = mFilter::hpfilter(sav_gdp, type = "lambda", freq = 6.25)$trend,
         indt_trend = mFilter::hpfilter(ind_tx, type = "lambda", freq = 6.25)$trend,
         propt_trend = mFilter::hpfilter(Property_taxes, type = "lambda", freq = 6.25)$trend,
         pit_trend = mFilter::hpfilter(PIT, type = "lambda", freq = 6.25)$trend)

colnames(fh) <- sub("\\[,1]$", "", colnames(fh))

fh <- fh %>% arrange(idem,year) %>% group_by(idem) %>% 
         filter(!is.na(Gini_net)) %>% 
         mutate(gi_cycle = mFilter::hpfilter(Gini_net, type = "lambda", freq = 6.25)$cycle,
         ed_cycle = mFilter::hpfilter(Education_exp, type = "lambda", freq = 6.25)$cycle,
         he_cycle = mFilter::hpfilter(Health_exp, type = "lambda", freq = 6.25)$cycle,
         soc_cycle = mFilter::hpfilter(Soc_payable, type = "lambda", freq = 6.25)$cycle,
         gov_cycle = mFilter::hpfilter(Gov_ex, type = "lambda", freq = 6.25)$cycle,
         kind_cycle = mFilter::hpfilter(Soc_kind, type = "lambda", freq = 6.25)$cycle,
         gdp_cycle = mFilter::hpfilter(gdp_gro, type = "lambda", freq = 6.25)$cycle,
         def_cycle = mFilter::hpfilter(Deficit, type = "lambda", freq = 6.25)$cycle,
         sav_cycle = mFilter::hpfilter(sav_gdp, type = "lambda", freq = 6.25)$cycle,
         indt_cycle = mFilter::hpfilter(ind_tx, type = "lambda", freq = 6.25)$cycle,
         propt_cycle = mFilter::hpfilter(Property_taxes, type = "lambda", freq = 6.25)$cycle,
         pit_cycle = mFilter::hpfilter(PIT, type = "lambda", freq = 6.25)$cycle
         )


fh <- fh %>% 
    mutate(gi_bb = case_when((gi_cycle > 0 ~ 1), (gi_cycle < 0 ~ 0)),
    ed_bb = case_when((ed_cycle > 0 ~ 1), (ed_cycle < 0 ~ 0)),
    he_bb = case_when((he_cycle > 0 ~ 1), (he_cycle < 0 ~ 0)),
    soc_bb = case_when((soc_cycle > 0 ~ 1), (soc_cycle < 0 ~ 0)),
    kind_bb = case_when((kind_cycle > 0 ~ 1), (kind_cycle < 0 ~ 0)),
    gdp_bb = case_when((gdp_cycle > 0 ~ 1), (gdp_cycle < 0 ~ 0)),
    # prt_bb = case_when((prt_cycle > 0 ~ 1), (prt_cycle < 0 ~ 0)),
    # indt_bb = case_when((indt_cycle > 0 ~ 1), (indt_cycle < 0 ~ 0)),
    # pit_bb = case_when((pit_cycle > 0 ~ 1), (pit_cycle < 0 ~ 0))
    )

rm(temp)
detach("package:mFilter", unload = TRUE)
```


```{r}
namemean = name[! name %in% c('idem', 'year', 'serie')]
```

```{r}
dm = demean(hp, select=~Gini_net+gdp_gro+Gov_ex+Education_exp+Health_exp+Soc_payable, group="idem", suffix_demean="_within")

dm <- dm %>% select(ends_with('_within'))

colnames(dm) <- gsub("_within","_dm",colnames(dm))

dm['idem'] = hp$idem
dm['year'] = hp$year
dm['serie'] = hp$serie

dm <- dm[, c(7,8,9,1,2,3,4,5)]

detach("package:datawizard", unload = TRUE)

hp = merge.data.frame(fh, dm, by=c("idem","year","serie"))

library("writexl")
write_xlsx(hp,"C:/Users/canut/Desktop/clean_t.xlsx")

detach("package:writexl", unload = TRUE)
```

