<<<<<<< HEAD
---
title: "dp"
author: "Daniel H."
date: "7/8/2020"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r, message = off, warning=FALSE}
library(tidyverse)
library(readxl)
library(lmtest)

#library(psych)
```


```{r}
ine <- read_excel("D:/ECB/INEQUALITY/2020/FINAL 04.xlsx", sheet = "log (2)")

ine <-  as.data.frame(ine)
ine2 <- drop_na(ine)

```


le_female, net_len_w/i, soc_payable, gov_ex, soc_prot, td_female, tertiary_ed, voice, ruleoflaw, goveff, soc_proc_ex_pen, trade, 


Data Panel modelling

```{r}
attach(ine)

lmg = lm(Gini_net ~ GDP_pc + Soc_payable + Gov_debt+Tertiary_ed_diff+ruleoflaw, data=ine)

coeftest(lmg, type = "HC0")
```

```{r}
library(plm)

#FE
# markdepth or finadeve
# TRANSFERS
# Soc_payable, Social_prot
# KIND
# Education_exp
# PROG
# mrp_all*ind_tx
# Deficit+Unempl_rateD
# Secondary_ed

# finadeve + gro_GDPpc + Gov_ex + Secondary_ed + Trade

E <- pdata.frame(ine, index=c("idem","year"), drop.index=TRUE, row.names=TRUE)

ine3 = ine
ine3$idem <- NULL
ine3$debt_g <- NULL
ine3$year <- NULL
ine3$Gini_net <- NULL

na = names(ine3)
na1 = names(ine3)

na = str_remove_all(na, "Gini_net")
na = str_remove_all(na, "Gini_market")
na = str_remove_all(na, "Deciles")
na = str_remove_all(na, "ba_40%")
na = str_remove_all(na, "Quantiles")
na = str_remove_all(na, "idem")
na = str_remove_all(na, "year")
na = str_remove_all(na, "debt_g")

na['1']

fm <- as.formula(paste(paste(na, collapse= "+")))

attach(ine)

all <- lm(Gini_net ~ Gov_debt + Life_xpectancy + Health_exp + Wages + HICP + 
     ac_pop + pop + Education_exp + Social_prot_ex_pen +Family+ Unemp_tra + Unempl_rate+HICP+Wages+Labour_income+Corporate_ta+property_tx+`prod&imp_tx`+
       ind_tx+ac_pop+pop+ `gro%pop`+`gro%GDP`+ Net_mig + Trade + TOT + GDP_curr + GDP_con +  GDP_pc + gro_GDPpc + Net_len_adj + Net_len_wi + Secondary_ed + 
    Tertiary_ed + Tertiary_ed_diff + leavers + le_male + le_female + Gov_inv + Gov_ex + Deficit + Soc_payable + Soc_kind + employ_rate + arp_mid + mrp_all + goveff + regqua +  ruleoflaw + voice + finadeve + fininsti + finmarket + instdepth + insaccess + ins_effic + markdepth + markaccess + mark_effic, data = ine)

##
backwardElimination <- function(x, sl) {
  numVars = 35
  for (i in c(1:numVars)){
    regressor = lm(formula = Gini_net ~ Life_xpectancy + Health_exp + HICP + ac_pop + Social_prot_ex_pen +Family+ Unemp_tra + HICP + Corporate_ta + `prod&imp_tx` + ind_tx + `gro%pop` +  Net_mig + Trade + TOT + gro_GDPpc + Net_len_adj + Net_len_wi + leavers + le_male + Gov_inv + Gov_ex + Deficit + Soc_payable + Soc_kind + employ_rate + arp_mid + mrp_all + goveff + voice + fininsti + finmarket + instdepth + insaccess + markdepth + markaccess + mark_effic, data = ine)
    
    maxVar = max(coef(summary(regressor))[c(1:numVars), "Pr(>|t|)"])
    if (maxVar > sl){
      j = which(coef(summary(regressor))[c(1:numVars), "Pr(>|t|)"] == maxVar)
      x = x[, -j]
    }
    numVars = numVars - 1
  }
  return(summary(regressor))
}

SL = 0.05
#dataset = ine[, c(1,2,3,4,5)]
backwardElimination(ine, SL)

##

coeftest(all, vcov. = vcovHC, type = "HC1")

pfe <- plm(Gini_net ~ lag(diff(GDP_con)) + lag(Secondary_ed) + lag(Trade)
+ Gov_ex , data = ine, model = "within", index = 'idem')

coeftest(pfe, vcov. = vcovHC, type = "HC1")
```

```{r}
### SUbSaMPLE
attach(ine)

ine3 = subset(ine, select = c(Gini_net, GDP_con, Secondary_ed, Gov_ex, Trade, Net_len_wi, 
     goveff, instdepth, insaccess, ins_effic, Health_exp, Education_exp, ind_tx,arp_mid, 
     Social_prot, Social_prot_ex_pen, Soc_kind,Soc_payable, Unemp_tra, Family, idem , year))

```


```{r}
library(ggplot2)
ggplot(ine, aes(x = year, y = (Net_len_wi), colour = idem)) +
  geom_point() + facet_wrap( ~ idem)


#DIFF LAG
ine <- ine %>%
 group_by(idem) %>% mutate(GDP_D = GDP_con-lag(GDP_con))


ine <- ine %>%
    group_by(idem) %>%
    mutate(GDP_LD = dplyr::lag(GDP_D, n = 1, default = NA))

# LAG

ine <- ine %>%
    group_by(idem) %>%
    mutate(Trade_L = dplyr::lag(Trade, n = 1, default = NA))

ine <- ine %>%
    group_by(idem) %>%
    mutate(Sec_L = dplyr::lag(Secondary_ed, n = 1, default = NA))

ine <- ine %>%
    group_by(idem) %>%
    mutate(GovX_L = dplyr::lag(Gov_ex, n = 1, default = NA))

ine <- ine %>%
 group_by(idem) %>% mutate(Netwi_D = Net_len_wi-lag(Net_len_wi))

ine <- ine %>%
    group_by(idem) %>%
    mutate(le_male_L = dplyr::lag(le_male, n = 1, default = NA))
```

```{r}
# OTROS MODELOS

pfe <- plm(Gini_net ~ lag(Gini_net) + (diff(GDP_con)) + (Secondary_ed) + (Trade) + Gov_ex + Gini_market + lag(Soc_payable, c(0), data = ine, model = "within", effect = "individual")

coeftest(pfe, vcov. = vcovHC, type = "HC1")

tfe <- plm(Gini_net ~ lag(Gini_net) + (diff(GDP_con)) + (Secondary_ed) + (Trade) + Gov_ex + Gini_market + Soc_payable, data = ine, model = "within", effect = "twoways")

coeftest(tfe, vcov. = vcovHC, type = "HC1")

rfe <- plm(Gini_net ~ lag(Gini_net) + lag(diff(GDP_con)) + lag(Secondary_ed) + lag(Trade) + Gov_ex, data = E, model = "random")

coeftest(rfe, vcov. = vcovHC, type = "HC1")

# efectos fijos de cada país
summary(fixef(pfe, type = "dfirst"))

# efectos fijos para cada año
summary(fixef(tfe, effect =  "time"))

summary(rfe)
summary(pfe)
punbalancedness(pfe)
summary(tfe)

## TEST FOR THE MODELS
plmtest(pfe,  effect="individual")

tfe <- plm(Gini_net ~ lag(diff(GDP_con)) + lag(Secondary_ed) + lag(Trade)
+ Gov_ex , data = E, model = "within", effect="time")


### ---------- Modelos mas eficientes sin lags en otra variables inden
pfe1 <- plm(Gini_net ~ lag(Gini_net) + Gini_market + lag(diff(GDP_con), c(0,1)) + (Secondary_ed) + (Trade) + Gov_ex +lag(Soc_payable,c(0,1)) , data = E, model = "within", effect = "individual")

tfe1 <- plm(Gini_net ~ lag(diff(GDP_con),c(0,1)) + (Secondary_ed) + (Trade)
+ Gov_ex , data = E, model = "within", effect="time")

# ------------------

coeftest(pfe1, vcov. = vcovHC, type = "HC1")


library(texreg)

screenreg(list(pfe, tfe), custom.model.names = c('FE', 'TE'))

phtest(pfe, rfe) # hausman test menor que 5% aceptar FE
#phtest(pfe, tfe)

# This function enables the estimation of the variance components of a panel model.

ercomp(Gini_net ~ lag(diff(GDP_con)) + lag(Secondary_ed) + lag(Trade)
+ Gov_ex, data=E, model='within', effect = "twoways")


# solve cross-sectional dependence
pcdtest(pfe, test = c("lm"))
pcdtest(pfe, test = c("cd"))

# Serial correlation si menor 5%
pbgtest(pfe)

# We can correct for serial correlation

pfe_hac <- coeftest(pfe, vcov = vcovHC(pfe, method = "arellano", type = "HC3"))

tfe_hac <- coeftest(tfe, vcov = vcovHC(tfe, method = "arellano", type = "HC3"))

screenreg(list(pfe_hac, tfe_hac), custom.model.names = c('FE-cor', 'TE-cor'))

## cross-sectional dependence and we need to correct it

pfe_cde <- coeftest(pfe, vcov = vcovHC(pfe, type="HC3", cluster = "group"))

tfe_cde <- coeftest(tfe, vcov = vcovHC(pfe, type="HC3", cluster = "group"))

screenreg(list(pfe_cde, tfe_cde), custom.model.names = c('FE-cor', 'TE-cor'))

## The cross-sectional and serial correlation (SCC) 

# Este es el mejor modelo

pfe_scc <- coeftest(pfe, vcov = vcovSCC(pfe, type="HC3", cluster = "group"))

tfe_scc <- coeftest(tfe, vcov = vcovSCC(pfe, type="HC3", cluster = "group"))

## MODELO EFICIENTES
pfe_scc1 <- coeftest(pfe1, vcov = vcovSCC(pfe1, type="HC3", cluster = "group"))

tfe_scc1 <- coeftest(tfe1, vcov = vcovSCC(tfe1, type="HC3", cluster = "group"))

phtest(tfe1, pfe1)
# -----------------------

screenreg(list(pfe_scc, tfe_scc), custom.model.names = c('FE-cor', 'TE-cor'))

screenreg(list(pfe_scc, tfe_scc, pfe, tfe), custom.model.names = c('FE-cor', 'TE-cor', 'PFE', 'TFE'))

screenreg(list(pfe_scc, tfe_scc, pfe_scc1, tfe_scc1), custom.model.names = c('FE-cor', 'TE-cor', 'PFE', 'TFE'))

# The Dickey-Fuller si pv menor que 5% no unit root
library(tseries)
adf.test(inef$Gini_net, k=2)

# Breusch-Pagan si pv menor que 5% heteroscedasticidad
library(lmtest)
bptest(Gini_net ~ `gro%GDP` + factor(idem), data = E, studentize=F)

#https://www.princeton.edu/~otorres/Panel101R.pdf - ultimas paginas

coeftest(pfe, vcovHC(pfe, method='white2'))

#FE
tfe <- plm(Gini_net ~ Trade+`gro%GDP`+Gov_ex, data = inef,
                    index = c("idem", "year"), 
                    model = "within", effect = 'twoways')

coeftest(tfe, vcov. = vcovHC, type = "HC1")
```

```{r}
linearHypothesis(tfe,test = "F",
                 c("GDP_pc=0", "ruleoflaw=0", "Gov_debt"), 
                 vcov. = vcovHC, type = "HC1")
```

H0 = los betas son igales a cero, si PF tiene estrella RH0


```{r}
library(stargazer)

rob_se <- list(sqrt(diag(vcovHC(pfe, , type = "HC1"))),
               sqrt(diag(vcovHC(tfe, , type = "HC1"))))

stargazer(pfe, tfe, digits = 3, 
          se = rob_se, align=TRUE,
          title = "Linear Panel Regression Models",
          model.numbers = T,
          column.labels = c("(1)", "(2)"), ci=TRUE, ci.level=0.90, single.row=TRUE)
```

```{r}
#devtools::install_github("joachim-gassen/ExPanDaR")
library(ExPanDaR)

ExPanD()
```

```{r}
E$debt_g <- NULL
ine2$year <- NULL
ine2$idem <- NULL
ine2$debt_g <- NULL

data("EmplUK", package="plm")
data("Produc", package="plm")
data("Grunfeld", package="plm")
data("Wages", package="plm")

gmm <- pgmm(GDP_pc ~ Trade+TOT | lag(GDP_pc,0:3)
               , data = ine, effect = "twoways", model = "twosteps")

summary(gmm)
```


```{r}
library(plm)

pgmm(formula = log(emp) ~ lag(log(emp), 1:2) + lag(log(wage), 
   0:1) + log(capital) + lag(log(output), 0:1) | lag(log(emp), 
    2:99), data = EmplUK, effect = "twoways", model = "twosteps")
```

```{r}

gr = pgmm(formula = Gini_net ~ lag(Gini_net, 1:2) + lag(diff(GDP_con),0:1) + lag(Soc_kind, 0:1) + lag(diff(TOT), 0:1) + Trade | 
  lag(Gini_net, 2:99) + lag(diff(GDP_con),4:99) + lag(Soc_kind, 2:99) , 
  data = ine, 
  effect = "individual", model = "twosteps", transformation = 'd', collapse = F,
)

summary(gr)



gr1 = pgmm(formula = Gini_net ~ lag(Gini_net, 1:2) + lag(diff(GDP_con),0:1) + (Secondary_ed) + (Trade) + Gov_ex + Gini_market + Soc_payable | 
  lag(Gini_net, 2:99) + lag(diff(GDP_con),4:99) , 
  data = ine, 
  effect = "individual", model = "twosteps", transformation = 'd', collapse = F,
)

screenreg(list(gr, gr1), custom.model.names = c('FE', 'TE'))

```

```{r}

ex2_abdata <-pvargmm(
dependent_vars = c("Gini_net", 'gro_GDPpc', 'Soc_payable'),
lags = 2,
predet_vars = c('Gov_ex','Gini_market'),
exog_vars = c("TOT","Trade",'Secondary_ed'),
transformation = "fod",
data = ine,
panel_identifier = c("idem", "year"),
steps = c("twostep"),
system_instruments = TRUE,
max_instr_dependent_vars = 3,
max_instr_predet_vars = 3,
min_instr_dependent_vars = 1L,
min_instr_predet_vars = 1L,
collapse = FALSE
)


#data("ex2_abdata")
summary(ex2_abdata)
```

# Seleccion de variables DEf 1.

https://rpubs.com/lijunjie/pvar


```{r}
#install.packages('pacman')
library(pacman)
p_load(tidyverse,panelvar)


pv21 <- pvargmm(
  dependent_vars = c("Gini_net", 'Soc_payable', 'gro_GDPpc'),
  lags = 2, # Number of lags of dependent variables
  predet_vars = c('Gov_ex', 'Gini_market'),
  exog_vars = c('Trade', 'Secondary_ed'),
  transformation = "fod",  # First-difference "fd" or forward orthogonal deviations "fod"
  data = ine,
  panel_identifier = c("idem", "year"),  # Vector of panel identifiers
  steps = c("twostep"),   # "onestep", "twostep" or "mstep" estimation
  system_instruments = T,
  max_instr_dependent_vars = 2,
  max_instr_predet_vars = 2,
  min_instr_dependent_vars = 1L,
  min_instr_predet_vars = 1L,
  collapse = T
)

summary(pv21)

## Necesito lags de variables predert..

Andrews_Lu_MMSC(pv1, HQ_criterion = 2.1)
Andrews_Lu_MMSC(pv2, HQ_criterion = 2.1)
Andrews_Lu_MMSC(pv21, HQ_criterion = 2.1)

# Se compara con varios modelos con rezagos y se escoge el que sea menor 
# incluye el signo negativo

h1 = stability(pv1)
h1
plot(h1)

ex1 = oirf(pv21, n.ahead = 5)
ex1_i = girf(pv21, n.ahead = 5, ma_approx_steps= 5)

pv_bs <-  bootstrap_irf(
  pv21,  typeof_irf = c("GIRF"), n.ahead = 5,
    nof_Nstar_draws = 5,  confidence.band = 0.90)

plot(ex1_i, pv_bs)


pv2 <- pvarfeols(
  dependent_vars = c("Gini_net", 'Soc_payable', 'gro_GDPpc'),
  lags = 3, # Number of lags of dependent variables
  exog_vars = c('Trade' , 'Gov_ex', 'Secondary_ed'),
  transformation = "demean",  data = ine,
  panel_identifier = c("idem", "year"))

pv2


h2 = stability(pv2)
h2
plot(h2)

ex2 = oirf(pv2, n.ahead = 9)
ex2_i = girf(pv2, n.ahead = 9, ma_approx_steps= 9)

plot(ex2_i)

```


