---
title: "jorda"
output: html_document
date: '2022-05-07'
---


```{r,message=FALSE}
library(tidyverse)
library(lpirfs)
library(dplyr)
library(jtools)
library(nlme)

library(broom)
library(scales)
library(truncnorm)
library(ipw)
library(WeightIt)

```

```{r load DB, message=FALSE, warning=FALSE}
library(readr)

ln1 <- read_delim("ln1.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)
ia1 <- read_delim("ia1.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)
ia2 <- read_delim("ia2.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)
ia3 <- read_delim("ia3.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)
ia4 <- read_delim("ia4.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)
ia5 <- read_delim("ia5.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)

attach(ia1)
```

```{r}
# ia6 <- as.data.frame(ia6 %>%
#   arrange(idem, year) %>%  # Sort by firm and tsocn by year
#   group_by(idem) %>%      # Tell dplyr to go within each firm
#   mutate(gdppc_gro = GDP_pc/(lag(GDP_pc)-1),
#          gdp_gro = GDP/(lag(GDP)-1),
#          insde_d = ins_effic/(lag(ins_effic)-1),
#          tot_d = TOT/(lag(TOT)-1),
#          debt_d = Gov_debt/(lag(Gov_debt)-1),
#          redis = Gini_market - Gini_net/Gini_net,
#          pi_m = PIT*mrp_all,
#          pi_a = PIT*arp_mid,
#          rd = sav_gdp*res_1mill,
#          rd1= sav_gdp*RD_gdp,
#          dtrade = Trade-lag(Trade),
#          lgini = lag(Gini_net),
#          lgdpg = lag(gdp_gro),
#          leduc = lag(Education_exp),
#          lkind = lag(Soc_kind), lpay=lag(Soc_payable)))
```

```{r}
#  No CORRER YA DEFINIDO EN VARIABLES

# library(datawizard)
# 
# dm = demean(ia6, select = ~ Gini_net+ gdp_gro, group = "idem", suffix_demean = "_within")
# 
# dm <- dm %>% select(ends_with('_within'))
# 
# colnames(dm)<-gsub("_within","dm",colnames(dm))
# 
# ia1 = cbind(ia1, dm)
# ia2 = cbind(ia2, dm)
# ia3 = cbind(ia3, dm)
# ia4 = cbind(ia4, dm)
# ia5 = cbind(ia5, dm)
# ia6 = cbind(ia6, dm)
# 
# ia1 = select(ia1,-123,-124)

```
Demeaned formula

https://ds4ps.org/pe4ps-textbook/docs/p-040-fixed-effects.html



```{r}
# ia1  <- ia1 %>%
#   group_by(idem) %>%
#   mutate( mean.pit=mean(PIT), pit.demeaned = PIT - mean.pit) %>%
# ungroup()
```


```{r}
# ln1 <- ln1 %>%
#   mutate(dumm = ifelse( year %in% c(1991, 1992, 2000, 2001, 2008, 2009, 2011, 2013), 1, NA))
# 
# ia1 <- ia1 %>%
#   mutate(dumm = ifelse( year %in% c(1991, 1992,2000, 2001, 2008, 2009, 2011, 2013), 1, 0))
# 
# ia2 <- ia2 %>%
#   mutate(dumm = ifelse( year %in% c(1991, 1992,2000, 2001, 2008, 2009, 2011, 2013), 1, 0))

b1 = ia1 %>% select(everything()) %>% filter(year %in% c(1991, 1992, 1993, 2000, 2001, 2008, 2009, 2011, 2012, 2013))
b2 = ia2 %>% select(everything()) %>%  filter(year %in% c(1991, 1992, 1993, 2000, 2001, 2008, 2009, 2011, 2012, 2013))
b3 = ia3 %>% select(everything()) %>% filter(year %in% c(1991, 1992, 1993, 2000, 2001, 2008, 2009, 2011, 2012, 2013))
b4 = ia4 %>% select(everything()) %>% filter(year %in% c(2008, 2009, 2011, 2012, 2013))

bo1 = ia1 %>% select(everything()) %>% filter (year %in% c(1994,1995,1996,1997,1998,2003,2004,2005,2006,2010,2015,2016,2017,2018))
bo2 = ia2 %>% select(everything()) %>% filter (year %in% c(1994,1995,1996,1997,1998,2003,2004,2005,2006,2010,2015,2016,2017,2018))
bo3 = ia3 %>% select(everything()) %>% filter (year %in% c(1994,1995,1996,1997,1998,2003,2004,2005,2006,2010,2015,2016,2017,2018))
bo4 = ia4 %>% select(everything()) %>% filter (year %in% c(1994,1995,1996,1997,1998,2003,2004,2005,2006,2010,2015,2016,2017,2018))
bo5 = ia5 %>% select(everything()) %>% filter (year %in% c(1994,1995,1996,1997,1998,2003,2004,2005,2006,2010,2015,2016,2017,2018))

```

```{r}
get_phat <- function(equation, db) {
    pror1 = glm(equation, data=db, family=binomial(link="probit"), na.action = na.exclude)

    db['phat0'] = predict(pror1,  type = 'response')
    db['invwt'] = db$ed_bb/db$phat0 + (1-db$ed_bb)/(1-db$phat0)
    
    db['phat'] = db$phat0
    
    lo = summary(db$phat0)[1]*1.1
    up = .9*summary(db$phat0)[6]
    
    db <- db %>% mutate(phat = ifelse(phat > up, up , db$phat))
    db <- db %>% mutate(phat = ifelse(phat < lo, lo, db$phat))
    
    return(db)
}

db_trunc <- function(db) {
    db['phat'] = db$phat0
    
    lo = summary(db$phat0)[1]*1.1
    up = .9*summary(db$phat0)[6]
    
    db <- db %>% mutate(phat = ifelse(phat > up, up , db$phat))
    db <- db %>% mutate(phat = ifelse(phat < lo, lo, db$phat))
    return(db)
    }
```


```{r}
eq_ed <- as.formula(paste("ed_bb ~ lag(Gini_netdm,1) + lag(Education_expdm,1)+ Gov_ex + Trade+Deficit+idem-1", collapse = " + "))

eq_he <- as.formula(paste("he_bb ~ lag(Gini_netdm,1) + Gov_ex+ lag(Health_expdm,1) + Trade+Deficit+idem-1", collapse = " + "))

eq_soc <- as.formula(paste("soc_bb ~ lag(Gini_netdm,1) +lag(Soc_payabledm,1)+ gdp_gro+Gov_ex +Trade+Deficit+idem-1", collapse = " + "))

eq_kind <- as.formula(paste("kind_bb ~ lag(Gini_netdm,1) +lag(Soc_kinddm,1)+Gov_ex +Trade+Deficit+idem-1", collapse = " + "))

eq_prt <- as.formula(paste("prt_bb ~ Gini_netdm +Property_taxesdm +Gov_ex+Trade+Deficit+idem", collapse = " + "))

eq_indtx <- as.formula(paste("indt_bb ~ lag(Gini_netdm,1) + lag(ind_txdm,1) + Gov_ex +Deficit+idem", collapse = " + "))

eq_pit <- as.formula(paste("pit_bb ~ lag(Gini_netdm,3)+lag(PITdm,4)+lag(gdp_grodm,3) + Gov_ex+ Deficit+idem-1", collapse = " + "))

```


```{r}
get_phat(eq_kind, ia1)

# data_frames <- list(ia1, ia2, ia3, ia4, ia5)

# results <- lapply(data_frames, function(df) get_phat(eq_ed, df))

```


```{r}
plot(ia1$invwt, ia1$Gini_net)
```



```{r}
pror1 = glm(ed_bb ~ lag(Gini_netdm,1) + lag(Education_expdm,1)+ Gov_ex + Trade+Deficit+idem-1, data=ia1, family=binomial(link="probit"), na.action = na.exclude)
summ(pror1)

ia1['phat0'] = predict(pror1,  type = 'response')

ia1['invwt'] = ia1$ed_bb/ia1$phat0 + (1-ia1$ed_bb)/(1-ia1$phat0)
```

```{r}
# Load the package
boxplot(ia1$invwt, plot=TRUE)$out

outliers <- boxplot(ia1$invwt, plot=FALSE)$out

boxplot(outliers, plot=TRUE)$out

x<-ia1$invwt

ia1$invwt_2 <- ia1$invwt[-which(x %in% outliers),]

# Create a new column excluding outliers
ia1$invwt_2 <- ifelse(ia1$invwt %in% outliers, NA, ia1$invwt)

```


```{r}
pror1 = glm(he_bb ~ lag(Gini_netdm,1) + Gov_ex + lag(Health_expdm,1) + Trade + Deficit + idem - 1, data = ia1, family = binomial(link="probit"), na.action = na.exclude)

summ(pror1)

```

```{r}
pror1 = glm(soc_bb ~ lag(Gini_netdm,1) +lag(Soc_payabledm,1)+ gdp_gro+Gov_ex +Trade+Deficit+idem-1, data=ia1, family=binomial(link="probit"), na.action = na.exclude)
summ(pror1)
```

```{r}
pror1 = glm(kind_bb ~ lag(Gini_netdm,1) +lag(Soc_kinddm,1)+Gov_ex +Trade+Deficit+idem-1, data=ia1, family=binomial(link="probit"), na.action = na.exclude)
summ(pror1)
```

```{r}
pror1 = glm(prt_bb ~ Gini_netdm +Property_taxesdm +Gov_ex+Trade+Deficit+idem, data=ia1 , family=binomial(link="probit"), na.action = na.exclude)

summ(pror1)
```

```{r}
pror1 = glm(indt_bb ~ lag(Gini_netdm,1) +  lag(ind_txdm,1) + Gov_ex +Deficit+idem, data=ia1 , family=binomial(link="probit"), na.action = na.exclude)
summ(pror1)

```

```{r}
pror1 = glm(pit_bb ~ lag(Gini_netdm,3)+lag(PITdm,4) +lag(gdp_grodm,3) + Gov_ex+ Deficit+idem-1, data=ia1, family=binomial(link="probit"), na.action = na.exclude)
summ(pror1)
```

## Parte 4
```{r}
library(plm)
```


```{r}

fix <- plm(Gini_netdm ~ kind_bb + lag(gdp_grodm) + lag(Gov_ex) + Soc_kinddm , data=ia1, index=c("idem", "year"), model="within",weights = ia1$invwt)


summary(fix)

```

Probar select_col para IVREG

```{r}
select_col <- function(pror1, ia1, cols) {
  esample <- rownames(as.matrix(pror1$fitted.values))

  ia1_e <- ia1[esample,]
  df_ee <- ia1_e %>% select(cols)
  return(df_ee)
}


# ia1['phat0'] = predict(pror1, type='response')

esample.n <- nobs(fix)
esample<-rownames(as.matrix(fix$model))
ia1_e = ia1[esample,]

# predict(fix, ia1_p, type='response', na.fill=TRUE)

ia1_e <- pdata.frame(ia1_e, index = c("idem", "year"))

# ia1_p['ed_bb_t'] = ifelse(ia1_p$ed_bb == 0, 1, 0)

ia1_e['mu0'] <- predict(fix, newdata=ia1_e, type="response")

ia1_e['mu0'] = ifelse(ia1_e$ed_bb==0 & !is.na(ia1_e$mu0),1,0)

```

```{r}
apply_prediction <- function(fix, db) {

  esample.n <- nobs(fix)
  esample <- rownames(as.matrix(fix$model))

  db_e <- db[esample, ]
  db_e <- (db_e)
  db_e$mu0 <- predict(fix, newdata = db_e, type = "response")
  db_e$mu0 <- ifelse(db_e$ed_bb == 0 & !is.na(db_e$mu0), 1, 0)
  
  return(db_e)
}

# Usage example
ia1_k <- apply_prediction(fix, ia1)

```

Note. Aqui deberias seleccionar columnas del modelo

```{r}

last_m <- function(n_db){
    
    n_db$mdiff = (-(n_db$gi_bb-n_db$phat)*n_db$mu1/n_db$phat)-((n_db$gi_bb-n_db$phat)*n_db$mu0/(1-n_db$phat))
# 
#     plot(n_db$mdiff, n_db$Gini_net)
    
    n_db$inv= ((n_db$gi_bb/n_db$phat) + (1-n_db$gi_bb)/(1-n_db$phat))
    n_db$iptw = (2*n_db$gi_bb-1)*(n_db$gi_bb*(n_db$inv))
    
    plot((n_db$inv),n_db$Gini_netdm)
    abline(lm(n_db$Gini_netdm ~ n_db$inv))
    
    n_db$dr1 = n_db$iptw+n_db$mdiff    
    
    # return(n_db)
    print(summary(lm(mdiff ~ 1, data=n_db)))
    
    
}

last_m(ia1_k)

```



```{r}

ia1_h$mdiff = (-(ia1_h$gi_bb-ia1_h$phat)*ia1_h$mu1/ia1_h$phat)-((ia1_h$gi_bb-ia1_h$phat)*ia1_h$mu0/(1-ia1_h$phat))

plot(ia1_h$mdiff, ia1_h$Gini_net)

ia1_h$inv= ((ia1_h$gi_bb/ia1_h$phat) + (1-ia1_h$gi_bb)/(1-ia1_h$phat))
ia1_h$iptw = (2*ia1_h$gi_bb-1)*(ia1_h$gi_bb*(ia1_h$inv))
plot(ia1_h$inv,ia1_h$Gini_net)

ia1_h$dr1 = ia1_h$iptw+ia1_h$mdiff

summary(lm(mdiff ~ 1, data=ia1_h))
```


```{r}
df_ee1 = select_col(pror1, ia1, c('idem','year',"ed_bb","Gini_netdm","Gov_ex","Education_expdm","Trade","Deficit"))

df_ee1 = select_col(pror1, ia1, c('idem','year',"he_bb","Gini_netdm","Gov_ex","Health_expdm","Trade","Deficit"))

df_ee1 = select_col(pror1, ia1, c('idem','year',"soc_bb","Gini_netdm","Gov_ex","Soc_payabledm",'gdp_gro',"Trade","Deficit"))

df_ee1 = select_col(pror1, ia1, c('idem','year',"kind_bb","Gini_netdm","Gov_ex","Soc_kinddm","Trade","Deficit"))

df_ee1 = select_col(pror1, ia1, c('idem','year',"prt_bb","Gini_netdm","Gov_ex","Property_taxesdm","Trade","Deficit"))

df_ee1 = select_col(pror1, ia1, c('idem','year',"indt_bb","Gini_netdm","Gov_ex","ind_txdm","Deficit"))

df_ee1 = select_col(pror1, ia1, c('idem','year',"pit_bb","Gini_netdm","gdp_grodm","PITdm","Gov_ex","Deficit"))

```



```{r}
# ln1['phat0'] = predict(pror, type = 'response')
ia1['phat0'] = predict(pror1,  type = 'response')
ia2['phat0'] = predict(pror1, type = 'response')
ia3['phat0'] = predict(pror1,  type = 'response')
ia4['phat0'] = predict(pror1,  type = 'response')
ia5['phat0'] = predict(pror1,  type = 'response')

plot(ia1$phat0, ia6$phat0)

```




```{r}
summary(ia1$phat0)

# TRUNCATE AT 10%

ia1['phat'] = ia1$phat0

lo = summary(ia1$phat0)[1]*1.1
up = .9*summary(ia1$phat0)[6]

ia1 <- ia1 %>% mutate(phat = ifelse(phat > up, up , ia1$phat))
ia1 <- ia1 %>% mutate(phat = ifelse(phat < lo, lo, ia1$phat))

summary(ia1$phat)

```

MODELO NO TRUNCADO

```{r}

ia1['invwt'] = ia1$ed_bb/ia1$phat + (1-ia1$ed_bb)/(1-ia1$phat)
ia2['invwt'] = ia2$Education_exp/ia2$phat0 + (1-ia2$Education_exp)/(1-ia2$phat0)
ia3['invwt'] = ia3$Education_exp/ia3$phat0 + (1-ia3$Education_exp)/(1-ia3$phat0)
ia4['invwt'] = ia4$Education_exp/ia4$phat0 + (1-ia4$Education_exp)/(1-ia4$phat0)
ia5['invwt'] = ia5$Education_exp/ia5$phat0 + (1-ia5$Education_exp)/(1-ia5$phat0)
ia6['invwt'] = ia6$Education_exp/ia6$phat0 + (1-ia6$Education_exp)/(1-ia6$phat0)

plot(ia1$invwt, phat)

```

MODELO TRUNCADO

```{r}

ia1['invwt'] = ia1$Education_exp/ia1$phat + (1-ia1$Education_exp)/(1-ia1$phat)
ia2['invwt'] = ia2$Education_exp/ia1$phat + (1-ia2$Education_exp)/(1-ia1$phat)
ia3['invwt'] = ia3$Education_exp/ia1$phat + (1-ia3$Education_exp)/(1-ia1$phat)
ia4['invwt'] = ia4$Education_exp/ia1$phat + (1-ia4$Education_exp)/(1-ia1$phat)
ia5['invwt'] = ia5$Education_exp/ia1$phat + (1-ia5$Education_exp)/(1-ia1$phat)
ia6['invwt'] = ia6$Education_exp/ia1$phat + (1-ia6$Education_exp)/(1-ia1$phat)

```

```{r}
library(lmtest)
library(sandwich)
library(clipr)
library(plm)
```

```{r}

fix <- plm(Gini_netdm ~ ed_bb + lag(gdp_gro) + lag(Gov_ex) + Education_expdm + gdp_grodm,data=ia1, index=c("idem", "year"), model="within", weights = ia1$invwt)

summary(fix)
```


```{r}
# invr1 = lm(Gini_netdm ~ lag(gi_bb) +ed_bb + lag(Gov_ex) + employ_rate + idem -1, weights = invwt, data = ia1)

invr1 = gls(Gini_netdm ~ he_bb + lag(GDP_cycle) + lag(Gov_ex) + employ_rate -1 +idem, data=ia1, weights=varIdent(form = ~ invwt), na.action = na.omit, correlation = corAR1(form = ~ 1 | Gini_net))

# Education_expdm |gdp_grodm ~ Secondary_ed + Gov_ex + employ_rate + pop_gro
coef(summary(invr1))
summary(invr1)
intervals(invr1)

coefficients(invr1)[1]

ia1['mu0'] = (if_else(ia1$he_bb == 1, ia1$he_bb - coefficients(invr1)[1], 0))
ia1['mu1'] = (if_else(ia1$he_bb == 0, ia1$he_bb + coefficients(invr1)[1], 1))

ia1['mdiff'] = (-(ia1$gi_bb-ia1$phat)*ia1$mu1/ia1$phat)-((ia1$gi_bb-ia1$phat)*ia1$mu0/(1-ia1$phat))

plot(ia1$mdiff, Gini_net)

ia1['inv']= ((ia1$gi_bb/ia1$phat) + (1-ia1$gi_bb)/(1-ia1$phat))
ia1['iptw'] = (2*ia1$gi_bb-1)*(ia1$gi_bb*(ia1$inv))
plot((ia1$inv),Gini_net)

ia1['dr1'] = ia1$iptw+ia1$mdiff

summary(lm(mdiff ~ 1, data=ia1))
```

```{r}
invr1 <- gls(Gini_netdm ~ ed_bb +lag(Gini_net)+ lag(GDP_cycle) + lag(Gov_ex) -1,data=df, weights = varIdent(form = ~  invwt), na.action = na.omit, correlation = corAR1(form = ~ 1 | Gini_net))
```


```{r}

last_rf <- function(df, vari) {
  invr1 <- gls(Gini_netdm ~ he_bb +lag(Gini_net)+ lag(GDP_cycle) + lag(Gov_ex) +employ_rate -1 , data=df, weights = varIdent(form = ~  invwt), na.action = na.omit, correlation = corAR1(form = ~ 1 | Gini_net))
  # invr1 = lm(Gini_netdm ~ ed_bb +lag(GDP_cycle) + lag(Gov_ex) + employ_rate + idem -1, weights = invwt, data = ia1)
  
  df['mu0'] = (if_else(vari == 1, vari - coefficients(invr1)[1], 0))
  df['mu1'] = (if_else(vari == 0, vari + coefficients(invr1)[1], 1))

  df['mdiff'] = (-(df$he_bb-df$phat)*df$mu1/df$phat)-((df$he_bb-df$phat)*df$mu0/(1-df$phat))

  df['inv']= ((df$he_bb/df$phat) + (1-df$he_bb)/(1-df$phat))
  df['iptw'] = (2*df$he_bb-1)*(df$he_bb*df$inv)
    
  df['dr1'] = df$iptw+df$mdiff

   summary(lm(mdiff ~ 1, data=df))
}

my_list <- list(ia1, ia2, ia3, ia4, ia5)

lapply(my_list, function(x) last_rf(x,x$he_bb)) 



```


```{r}
ia1['pip_a'] = ia1$PIT*ia1$mrp_all
ia2['pip_a'] = ia2$PIT*ia2$mrp_all
ia3['pip_a'] = ia3$PIT*ia3$mrp_all
ia4['pip_a'] = ia4$PIT*ia4$mrp_all
ia5['pip_a'] = ia5$PIT*ia5$mrp_all
ia6['pip_a'] = ia6$PIT*ia6$mrp_all

```

Table 8.

```{r}
invr1 = opm(Gini_netdm ~ lag(gi_bb) +lag(gdp_grodm,1) + Education_expdm + lag(Gov_ex) + ed_bb, data = ia1, index = c('idem','year'), n.samp = 10000, add.time.indicators = FALSE, weights=invwt) 
# -- EDUCATION
summary(invr1)
# invr1 = lm(Gini_net ~ dplyr::lag(Gini_net,1) + dplyr::lag(Gini_netdm,1) + dplyr::lag(gdp_grodm,1) + (Health_exp) + Secondary_ed + employ_rate , weights = invwt, data = ia1) -- HEALTH

# invr1 = lm(Gini_net ~ dplyr::lag(Gini_netdm,1) + dplyr::lag(gdp_grodm,1) + dplyr::lag(gdp_grodm,2)+ dplyr::lag(Soc_payable,1)+dplyr::lag(Gov_ex,1)+Secondary_ed + employ_rate + dplyr::lag(Trade,1), weights = invwt, data = ia1) -- SOC PAYABLE

# invr1 = opm(Gini_net ~lag(gdp_gro,1) + Property_taxes + Gov_ex + Secondary_ed , data = ia1, index = c('idem','year'), n.samp = 10000, add.time.indicators = FALSE, weights=invwt)
# summary(invr1)

# invr1 = opm(Gini_net ~lag(gdp_gro,1) + ind_tx + Gov_ex + Secondary_ed , data = ia1, index = c('idem','year'), n.samp = 10000, add.time.indicators = FALSE, weights=invwt)
# summary(invr1) -- IND TAXES

# invr1 = opm(Gini_net ~lag(gdp_gro,1) + ia1$pip_a + mrp_all + PIT + Gov_ex + Secondary_ed , data = ia1, index = c('idem','year'), n.samp = 10000, add.time.indicators = FALSE, weights=invwt)
# summary(invr1) -- PIT

invr1 = opm(Gini_net ~lag(gdp_gro,1) + Soc_kind + Gov_ex + Secondary_ed , data = ia1, index = c('idem','year'), n.samp = 10000, add.time.indicators = FALSE, weights=invwt)
summary(invr1)

invr2 = opm(Gini_net ~lag(gdp_gro,1) + Soc_kind + Gov_ex + Secondary_ed , data = ia2, index = c('idem','year'), n.samp = 10000, add.time.indicators = FALSE, weights=invwt)
summary(invr2)

invr3 = opm(Gini_net ~lag(gdp_gro,1) + Soc_kind + Gov_ex + Secondary_ed , data = ia3, index = c('idem','year'), n.samp = 10000, add.time.indicators = FALSE, weights=invwt)
summary(invr3)

invr4 = opm(Gini_net ~lag(gdp_gro,1) + Soc_kind + Gov_ex + Secondary_ed , data = ia4, index = c('idem','year'), n.samp = 10000, add.time.indicators = FALSE, weights=invwt)
summary(invr4)

invr5 = opm(Gini_net ~lag(gdp_gro,1) + Soc_kind + Gov_ex + Secondary_ed , data = ia5, index = c('idem','year'), n.samp = 10000, add.time.indicators = FALSE, weights=invwt)
summary(invr5)

invr6 = opm(Gini_net ~lag(gdp_gro,1) + Soc_kind + Gov_ex + Secondary_ed , data = ia6, index = c('idem','year'), n.samp = 10000, add.time.indicators = FALSE, weights=invwt)
summary(invr6)


caterplot(invr1, 'beta', labels = c('growth','E', 'D','D'))

kind_beta = cbind.data.frame(invr1[["samples"]][["beta"]][,2], invr2[["samples"]][["beta"]][,2],
                           invr3[["samples"]][["beta"]][,2], invr4[["samples"]][["beta"]][,2],
                           invr5[["samples"]][["beta"]][,2], invr6[["samples"]][["beta"]][,2])

colnames(kind_beta) <- c("1", "2","3", "4","5", "6" ) 

# PREDICTION

# mu0 = predict(invr, type = 'response')
mu01 = predict(invr1, type = 'response')

library(dplyr)
library(ggplot2)

ia1 %>%
        filter(idem %in% c("Cyprus")) %>%
        ggplot() +
        aes(x = year, y = Soc_kind, colour = idem) +
        geom_line(size = 0.5) +
        scale_color_hue(direction = 1) +
        theme_minimal()

plot(mu01[3:10])

```



```{r}
write.csv(ln1,"ln1.csv",row.names = FALSE)
write.csv(ia1,"ia1.csv",row.names = FALSE)
write.csv(ia2,"ia2.csv",row.names = FALSE)
write.csv(ia3,"ia3.csv",row.names = FALSE)
write.csv(ia4,"ia4.csv",row.names = FALSE)
write.csv(ia5,"ia5.csv",row.names = FALSE)
write.csv(ia6,"ia6.csv",row.names = FALSE)

```

```{r}
write.csv(b1,"b1.csv",row.names = FALSE)
write.csv(b2,"b2.csv",row.names = FALSE)
write.csv(b3,"b3.csv",row.names = FALSE)
write.csv(b4,"b4.csv",row.names = FALSE)

write.csv(bo1,"bo1.csv",row.names = FALSE)
write.csv(bo2,"bo2.csv",row.names = FALSE)
write.csv(bo3,"bo3.csv",row.names = FALSE)
write.csv(bo4,"bo4.csv",row.names = FALSE)
write.csv(bo5,"bo5.csv",row.names = FALSE)
write.csv(bo6,"bo6.csv",row.names = FALSE)
```

tABLE 3 iv BINARY TREATMENT

```{r}

fix <- plm(Gini_netdm ~ kind_bb + lag(gdp_grodm) + lag(Gov_ex) + Soc_kinddm , data=ia1, index=c("idem", "year"), model="within",weights = ia1$invwt)



m_i <- plm(Gini_net ~ kind_bb , data = ia1, model="within", index=c("idem", "year"))

summary(m_i)


fit_df <- data.frame(fitted = plm:::fitted_exp.plm(m_i))

# Assign row names to the fitted data frame to match the original data
rownames(fit_df) <- row.names(m_i$model)

# Merge the fitted values with the original data using row names as the common identifier
ia1_i <- merge(ia1, fit_df, by = 0, all.x = TRUE)

esample.n <- nobs(m_i)
esample <- rownames(as.matrix(m_i$model))

db_e <- ia1_i[esample, ]
db_e <- data.frame(db_e, index=c("idem", "year"))
# Remove the redundant row name column
# ia1 <- subset(ia1, select = -c("Row.names", "Row.names.x"))

# Rename the Row.names.y column to Row.names
# colnames(ia1)[colnames(ia1) == "Row.names.y"] <- "Row.names"

ia1_i <- ia1_i[ -c(1,124) ]
ia_id = data.frame(ia1,)

db_e$mu0 <- predict(m_i, newdata = db_e, type = "response")
  db_e$mu0 <- ifelse(db_e$ed_bb == 0 & !is.na(db_e$mu0), 1, 0)

  
fit_df <- data.frame(predict(m_i, newdata = db_e, type = "response"))

# Assign row names to the fitted data frame to match the original data

apply_prediction <- function(fix, db) {

  esample.n <- nobs(fix)
  esample <- rownames(as.matrix(fix$model))

  db_e <- db[esample, ]
  db_e <- (db_e)
  db_e$mu0 <- predict(fix, newdata = db_e, type = "response")
  db_e$mu0 <- ifelse(db_e$ed_bb == 0 & !is.na(db_e$mu0), 1, 0)
  
  return(db_e)
}

# Usage example
ia1_k <- apply_prediction(fix, ia1)



ia1_i[rowSums(is.na(ia1_i)) == 0, ]
ia1_k %>% drop_na()
na.omit(ia1_i)
```

```{r}
# Obtain the predicted values
predicted_values <- predict(m_i, newdata = db_e, type = "response")

# Subset the original data frame to match the length of predicted values
db_e_subset <- db_e[1:length(predicted_values), ]

# Add the predicted values to the subset of the original data frame
db_e_subset$mu0 <- predicted_values

# Use the subsetted data frame with predicted values
db_e <- db_e_subset



```


```{r}
esample.n <- nobs(m_i)
esample <- rownames(as.matrix(m_i$model))

db_e <- ia1[esample, ]
db_e <- (db_e)

library(MatchIt)

matched_data <- matchit(kind_bb ~ Gini_netdm + gdp_grodm + Soc_kinddm + Gov_ex + Trade + Deficit+idem,
                        data = db_e,
                        method = "nearest",
                        distance = "mahalanobis",
                        replace = TRUE)

summary(matched_data)
```

```{r}
# Fit the model
model_wrong <- plm(Gini_net ~ kind_bb | lag(Soc_kind) + Gov_ex, data = ia1, index = c("idem", "year"), model = "within")

# Create an empty data frame to store the fitted values
fitted_df <- data.frame(fitted = plm:::fitted_exp.plm(model_wrong))

# Assign row names to the fitted data frame to match the original data
rownames(fitted_df) <- row.names(model_wrong$model)

# Merge the fitted values with the original data using row names as the common identifier
ia1 <- merge(ia1, fitted_df, by = 0, all.x = TRUE)

# Remove the redundant row name column
# ia1 <- subset(ia1, select = -c("Row.names", "Row.names.x"))

# Rename the Row.names.y column to Row.names
# colnames(ia1)[colnames(ia1) == "Row.names.y"] <- "Row.names"

ia1 <- ia1[ -c(1) ]
ia1 <- ia1[ -c(124) ]
```


```{r}
matched_data_for_real <- match.data(matched_data)
```

```{r}
model_matched <- lm(Gini_net ~ fitted.x  , 
                    data = matched_data_for_real,
                    weights = weights)
summary(model_matched)
```
Generate propensity scores

```{r}
model_net <- glm(kind_bb ~ Gini_netdm + Soc_kinddm + Gov_ex + Trade + Deficit+idem-1,
                 data = ia1_k,
                 family = binomial(link = "logit"))

summary(model_net, exponentiate = TRUE)
```

```{r}
net_probabilities <- augment_columns(model_net,
                                     ia1_k,type.predict = "response") %>% rename(propensity = .fitted)

# Look at the first few rows of a few columns
net_probabilities %>%  select(kind_bb, Gini_netdm, Soc_kinddm, Gov_ex, Trade, Deficit, idem) %>% 
  head()
```


```{r}
net_ipw <- net_probabilities %>% mutate(ipw = (kind_bb / propensity) + ((1 - kind_bb) / (1 - propensity)))

# Look at the first few rows of a few columns
net_ipw %>% 
  select(kind_bb, Gini_netdm, Gini_net, gdppc_gro, Soc_kinddm, Gov_ex, Trade, Deficit, idem, propensity, ipw, fitted.x) %>% 
  head()
```


```{r}
model_ipw <- lm(Gini_net ~ fitted.x, 
                data = net_ipw,
                weights = ipw)

summary(model_ipw)
```

```{r}
net_ipw <- net_ipw %>% 
  # If the IPW is larger than 8, make it 8, otherwise use the current IPW
  mutate(ipw_truncated = ifelse(ipw > 5, 5, ipw))

model_ipw_truncated <- lm(Gini_net ~ fitted.x, 
                        data = net_ipw,
                          weights = ipw_truncated)

summary(model_ipw_truncated)
```

```{r}
plot(net_ipw$propensity, net_ipw$Soc_kind)
abline(lm(Soc_kind~propensity,data=net_ipw),col='red')
```

