---
title: "R Notebook"
output:
  word_document: default
  html_notebook: default
---

```{r,message=FALSE}
library(tidyverse)
library(lpirfs)
library(dplyr)
```

```{r, message=FALSE}
library(readxl)
lpf <- read_excel("final.xlsx")
```

```{r}
fd <- as.data.frame(lpf %>%
  arrange(idem, year) %>%  # Sort by firm and then by year
  group_by(idem) %>%      # Tell dplyr to go within each firm
  mutate(gdppc_gro = GDP_pc/(lag(GDP_pc)-1),
         gdp_gro = GDP/(lag(GDP)-1),
         insde_d = ins_effic/(lag(ins_effic)-1),
         tot_d = TOT/(lag(TOT)-1),
         debt_d = Gov_debt/(lag(Gov_debt)-1),
         redis = Gini_market - Gini_net/Gini_net,
         pi_m = PIT*mrp_all,
         pi_a = PIT*arp_mid,
         rd = sav_gdp*res_1mill,
         rd1= sav_gdp*RD_gdp,
         dtrade = Trade-lag(Trade),
         lgini = lag(Gini_net),
         lgdpg = lag(gdp_gro),
         leduc = lag(Education_exp),
         lkind = lag(Soc_kind), lpay=lag(Soc_payable)))
```


```{r}
library(mFilter)
hp <- as.data.frame(lpf %>%
  arrange(idem, year) %>%  # Sort by firm and then by year
  group_by(idem) %>%      # Tell dplyr to go within each firm
  mutate_at(vars(Gini_net),~ifelse(is.na(.x), mean(.x, na.rm = TRUE), .x)))
```

```{r}
gi = hpfilter(na.omit(hp$Gini_net), freq = 6.25, type = 'frequency')

out <- cbind.data.frame(gi$cycle, gi$trend, gi$x, hp$idem, hp$year)
colnames(out) <- c("cycle", "trend",'x','idem','year')

out <- out %>% mutate( booms = case_when(cycle > 0 ~ 1),
                bust = case_when(cycle < 0 ~ 1),
                gi_bb = case_when((cycle > 0 ~ 1), (cycle < 0 ~ 0)))

write.csv(out, "hp.csv",  row.names = FALSE)
```


```{r}
# READ HP
sp =  data=subset(out1, idem=="Spain")

par(mfrow = c(2, 1), mar = c(3, 2, 2, 1))
plot(sp$year,sp$x, main = "Spain: Hodrick-Prescott filter Gini disp. income)")
lines(sp$year,sp$x, col = "steelblue")
lines(sp$year,sp$trend, col = "red")
plot(sp$year,sp$cycle, main = "Cyclical component (deviations from trend)")
lines(sp$year,sp$cycle, col = "steelblue")

```



```{r}
library(datawizard)

dm = demean(fd, select = ~ Gini_net+ gdp_gro+ Trade+ Gov_ex+ Secondary_ed+ employ_rate+          Education_exp+  Health_exp+  Soc_kind+ Soc_payable+ Social_prot_ex_pen+ Unemp_tra+Property_taxes+ PIT+ ind_tx+ Corporate_ta+ mrp_all+ arp_mid+ pi_a+ pi_m+ sav_gdp+ RD_gdp+ res_1mill+ rd+ rd1 + dtrade +
lgini+ lgdpg+ leduc+ lkind+ lpay, group = "idem", suffix_demean = "_within")

dm <-  dm %>% select(ends_with('_within'))

colnames(dm)<-gsub("_within","",colnames(dm))

dm['idem'] = fd$idem
dm['year'] = fd$year

dm <- dm %>% relocate(idem) 
dm <- dm %>% relocate(year, .after = idem) 

attach(dm)
```

## LOCAL IMPULSE ESTIMATIONS

```{r}
# Exclude observations
data_sample <- seq(1990, 2018)[which(!(seq(1990, 2018) %in% c(seq(1991, 1992),seq(2000, 2001), seq(2008, 2009), seq(2011, 2013))))]

```

```{r}
ln <- fd %>%
dplyr::select(idem, year, Gini_net, gdp_gro, Trade, Gov_ex, Secondary_ed, employ_rate,          Education_exp,  Health_exp,  Soc_kind, Soc_payable, Social_prot_ex_pen, Unemp_tra,Property_taxes, PIT, ind_tx, Corporate_ta, mrp_all, arp_mid, pi_a, pi_m, sav_gdp, RD_gdp, res_1mill, rd, rd1, Gov_debt)

ln <- cbind(ln, out[c("cycle", "trend", "gi_bb")])

attach(ln)

write.csv(ln,"iapw.csv",row.names = FALSE)
```


```{r}
library(pROC)

sample <- sample(c(TRUE, FALSE), nrow(ln), replace=TRUE, prob=c(0.75,0.25))
train <- ln[sample, ]
test <- ln[!sample, ] 

prob <- glm(lead(gi_bb,1) ~ Gov_ex + lag(gdp_gro,1) + lag(Gini_net,1) + sav_gdp + Secondary_ed , data=train, family=binomial(link="probit"))
summary(prob)

prob1 <- glm(lead(gi_bb,1) ~ Gov_ex + lag(gdp_gro,1) + lag(Gini_net,1) + Secondary_ed + sav_gdp + Soc_kind , data=train, family=binomial(link="probit"))
summary(prob1)

prob2 <- glm(lead(gi_bb,1) ~ Gov_ex + lag(gdp_gro,1) + lag(Gini_net,1)+ Secondary_ed + sav_gdp + ind_tx , data=train, family=binomial(link="probit"))
summary(prob2)

predicted <- predict(prob1, test, type="response")
#calculate AUC
auc(test$gi_bb, predicted)


```
```{r}
library(readr)
ia1 <- read_delim("ia1.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)
ia2 <- read_delim("ia2.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)
ia3 <- read_delim("ia3.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)
ia4 <- read_delim("ia4.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)
ia5 <- read_delim("ia5.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)
ia6 <- read_delim("ia6.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)


z = list(ia1,ia2,ia3,ia4,ia5,ia6)

```


```{r}
ln1 <- ln
# ln1 <- ln %>% drop_na()
pror = glm(gi_bb ~ lag(Gini_net,1) + gdp_gro + Gov_ex , data=ln1, family=binomial(link="probit"), na.action = na.exclude)

pror1 = glm(gi_bb ~ lag(Gini_net,1) + gdp_gro + Gov_ex , data=ia1, family=binomial(link="probit"), na.action = na.exclude)

pror2 = glm(gi_bb ~ lag(Gini_net,1) + gdp_gro + Gov_ex , data=ia2, family=binomial(link="probit"), na.action = na.exclude)

pror3 = glm(gi_bb ~ lag(Gini_net,1) + gdp_gro + Gov_ex , data=ia3, family=binomial(link="probit"), na.action = na.exclude)

pror4 = glm(gi_bb ~ lag(Gini_net,1) + gdp_gro + Gov_ex , data=ia4, family=binomial(link="probit"), na.action = na.exclude)

pror5 = glm(gi_bb ~ lag(Gini_net,1) + gdp_gro + Gov_ex , data=ia5, family=binomial(link="probit"), na.action = na.exclude)

pror6 = glm(gi_bb ~ lag(Gini_net,1) + gdp_gro + Gov_ex , data=ia6, family=binomial(link="probit"), na.action = na.exclude)


ln1['phat0'] = predict(pror, type = 'response')
ia1['phat0'] = predict(pror1, type = 'response')
ia2['phat0'] = predict(pror2, type = 'response')
ia3['phat0'] = predict(pror3, type = 'response')
ia4['phat0'] = predict(pror4, type = 'response')
ia5['phat0'] = predict(pror5, type = 'response')
ia6['phat0'] = predict(pror6, type = 'response')


ia1['invwt'] = ia1$gi_bb/ia1$phat0 + (1-ia1$gi_bb)/(1-ia1$phat0)
ia2['invwt'] = ia2$gi_bb/ia2$phat0 + (1-ia2$gi_bb)/(1-ia2$phat0)
ia3['invwt'] = ia3$gi_bb/ia3$phat0 + (1-ia3$gi_bb)/(1-ia3$phat0)
ia4['invwt'] = ia4$gi_bb/ia4$phat0 + (1-ia4$gi_bb)/(1-ia4$phat0)
ia5['invwt'] = ia5$gi_bb/ia5$phat0 + (1-ia5$gi_bb)/(1-ia5$phat0)
ia6['invwt'] = ia6$gi_bb/ia6$phat0 + (1-ia6$gi_bb)/(1-ia6$phat0)


```

```{r}
forvalues i=1/6 {
	* SAME OUTCOME REG IN BOTH T&C THIS TIME, REST ALL THE SAME
	/*qui*/ reg ly`i' ftreatment hply dml0dly  dml1dly dmdumiso1-dmdumiso16 [pweight=invwt] ///
		if year>=1980 & year<=2007,  cluster(iso)
	gen samp=e(sample) // set sample
	predict mu0 if samp==1 & ftreatment==0 // actual
	predict mu1 if samp==1 & ftreatment==1 // actual
	replace mu0 = mu1 -  [ftreatment] if samp==1 & ftreatment==1 // ghost
	replace mu1 = mu0 + _b[ftreatment] if samp==1 & ftreatment==0 // ghost
	*from Lunt et al
	generate mdiff1=(-(a-pihat0)*mu1/pihat0)-((a-pihat0)*mu0/(1-pihat0))
	generate iptw=(2*a-1)*ly`i'*invwt
	generate dr1=iptw+mdiff1
	qui gen ATE_IPWRA=1 // constant for convenience in next reg to get mean
	qui reg dr1 ATE_IPWRA, nocons cluster(iso)
	eststo DR1_`i'
	sum dr1
	local dr1m = r(mean)
	gen Isq  = (dr1-`dr1m')^2
	sum Isq
	estadd scalar RobustSE = sqrt(r(mean)/r(N))
	estadd scalar pvalue = normal(`dr1m'/sqrt(r(mean)/r(N)))	
	capture drop iptw Isq mdiff1 dr1 mu1 mu0 samp ATE_IPWRA
	capture scalar drop dr1m
	}
```

```{r}
library(lmtest)
library(sandwich)
library(plm)

invr = plm(Gini_net ~ gdp_gro + Secondary_ed + employ_rate + Gov_ex + Trade + gi_bb, weights = ln1$invmt, data = ln1, na.action = na.exclude, model = "within")

invr1 = plm(ia1$Gini_net ~ ia1$gdp_gro + ia1$Secondary_ed + ia1$employ_rate + ia1$Gov_ex + ia1$Trade + ia1$gi_bb, weights = ia1$invwt, data = ia1, na.action = na.exclude, model = "within")

invr2 = plm(ia2$Gini_net ~ ia2$gdp_gro + ia2$Secondary_ed + ia2$employ_rate + ia2$Gov_ex + ia2$Trade + ia2$gi_bb, weights = ia2$invwt, data = ia2, na.action = na.exclude, model = "within")

invr3 = plm(ia3$Gini_net ~ ia3$gdp_gro + ia3$Secondary_ed + ia3$employ_rate + ia3$Gov_ex + ia3$Trade + ia3$gi_bb, weights = ia3$invwt, data = ia3, na.action = na.exclude, model = "within")

invr4 = plm(ia4$Gini_net ~ ia4$gdp_gro + ia4$Secondary_ed + ia4$employ_rate + ia4$Gov_ex + ia4$Trade + ia4$gi_bb, weights = ia4$invwt, data = ia4, na.action = na.exclude, model = "within")

invr5 = plm(ia5$Gini_net ~ ia5$gdp_gro + ia5$Secondary_ed + ia5$employ_rate + ia5$Gov_ex + ia5$Trade + ia5$gi_bb, weights = ia5$invwt, data = ia5, na.action = na.exclude, model = "within")

invr6 = plm(ia6$Gini_net ~ ia6$gdp_gro + ia6$Secondary_ed + ia6$employ_rate + ia6$Gov_ex + ia6$Trade + ia6$gi_bb, weights = ia6$invwt, data = ia6, na.action = na.exclude, model = "within")

summary(invr)

tmr = coeftest(pror2, vcov = vcovHC(pror2, "white1"))
mu0 = predict(pror2, type = 'response')

ln1['mu'] = mu0*ln1$trend/ln1$trend

ln1 <- ln1 %>% mutate(mu0 = if_else(ln1$gi_bb == 0, 1, 0))
ln1['mu0'] = ln1$mu0*ln1$mu

ln1 <- ln1 %>% mutate(mu1 = if_else(ln1$gi_bb == 1, 1, 0))
ln1['mu1'] = ln1$mu1*ln1$mu

ln1['mdiff1']=(-(ln1$gi_bb -ln1$phat0)*ln1$mu1/ln1$phat0)-((ln1$gi_bb -ln1$phat0)*ln1$mu0/(1-ln1$phat0))
ln1['iptw'] = (2*ln1$gi_bb-1)*ln1$Gini_net*ln1$invwt
ln1['dr1']=ln1$iptw + ln1$mdiff1

attach(ln1)

summary(plm(ln1$Gini_net ~ ln1$dr1 + gdp_gro + Secondary_ed + employ_rate + Gov_ex + Trade, data = ln1, na.action = na.exclude, model = "within"))

```

```{r}
lp = lapply(z, function(x) 
    plm(Gini_net ~ gdp_gro + Secondary_ed + employ_rate + Gov_ex + Trade + gi_bb, weights = ln1$invmt, data = ln1, na.action = na.exclude, model = "within"))

```


## WITHOUT RECESSION

```{r, warning=FALSE}
p1 <-  lp_lin_panel(data_set          = dm,
                              # data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "Education_exp",
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                                gmm_model = 'twosteps', gmm_effect = 'individual',
                              instrum =   colnames(dm)[c(29,30,13)],
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('employ_rate','Gov_ex'),
                              lags_exog_data = 1,
                              l_exog_data    = colnames(dm)[c(23)],
                              l_fd_exog_data    = colnames(dm)[c(12,3)],
                              lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

lp1 = data.frame(x =1:5,estm=c(p1[["irf_panel_mean"]]),low=c(p1[["irf_panel_low"]]),up=c(p1[["irf_panel_up"]]))

p2 <-  lp_lin_panel(data_set          = dm,
                              # data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "Health_exp",
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                               gmm_model = 'twosteps', gmm_effect = 'individual',
                              instrum =   colnames(dm)[c(29,30)],
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('employ_rate','Gov_ex','Secondary_ed'),
                              lags_exog_data = 1,
                              l_exog_data    = colnames(dm)[c(23)],
                              l_fd_exog_data    = colnames(dm)[c(12,3)],
                              lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

lp2 = data.frame(x =1:5,estm=c(p2[["irf_panel_mean"]]),low=c(p2[["irf_panel_low"]]),up=c(p2[["irf_panel_up"]]))

p3 <-  lp_lin_panel(data_set          = dm,
                              # data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "Soc_kind",
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                                 gmm_model = 'twosteps', gmm_effect = 'individual',
                                instrum =   colnames(dm)[c(29,30)],
                                 robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                                 c_exog_data   = c('employ_rate','Gov_ex','Secondary_ed'),
                                lags_exog_data = 1,
                                l_exog_data    = colnames(dm)[c(23)],
                                l_fd_exog_data    = colnames(dm)[c(12,3)],
                                lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

lp3 = data.frame(x =1:5,estm=c(p3[["irf_panel_mean"]]),low=c(p3[["irf_panel_low"]]),up=c(p3[["irf_panel_up"]]))

p4 <-  lp_lin_panel(data_set          = dm,
                              # data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "Soc_payable",
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                                gmm_model = 'twosteps', gmm_effect = 'individual',
                                instrum =   colnames(dm)[c(29,30)],
                                 robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                                 c_exog_data   = c('employ_rate','Gov_ex','Secondary_ed'),
                                lags_exog_data = 1,
                                l_exog_data    = colnames(dm)[c(23)],
                                l_fd_exog_data    = colnames(dm)[c(12,3)],
                                lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

lp4 = data.frame(x =1:5,estm=c(p4[["irf_panel_mean"]]),low=c(p4[["irf_panel_low"]]),up=c(p4[["irf_panel_up"]]))

# No lo veo claro con Social pensions

p5 <-  lp_lin_panel(data_set          = dm,
                              # data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "Unemp_tra",
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                               gmm_model = 'twosteps', gmm_effect = 'individual',
                                instrum =   colnames(dm)[c(29,30,13)],
                                 robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                                 c_exog_data   = c('employ_rate','Gov_ex','Secondary_ed'),
                                lags_exog_data = 1,
                                l_exog_data    = colnames(dm)[c(23)],
                                l_fd_exog_data    = colnames(dm)[c(12,3)],
                                lags_fd_exog_data = 1, confint = 1.96, hor = 5)

lp5 = data.frame(x =1:5,estm=c(p5[["irf_panel_mean"]]),low=c(p5[["irf_panel_low"]]),up=c(p5[["irf_panel_up"]]))
```

## RECESSION SAMPLE

```{r, warning=FALSE}
pr1 <-  lp_lin_panel(data_set          = dm,
                               data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = ("leduc"),
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                              gmm_model = 'twosteps', gmm_effect = 'individual',
                              instrum =   colnames(dm)[c(29,30,13)],
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('employ_rate'),
                              lags_exog_data = 1,
                              l_exog_data    = colnames(dm)[c(23)],
                              l_fd_exog_data    = colnames(dm)[c(12,3,14)],
                              lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

lpr1 = data.frame(x =1:5, estm=c(pr1[["irf_panel_mean"]]),low=c(pr1[["irf_panel_low"]]),up=c(pr1[["irf_panel_up"]]))

pr2 <-  lp_lin_panel(data_set          = dm,
                              data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "Health_exp",
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                               gmm_model = 'twosteps', gmm_effect = 'individual',
                              instrum =   colnames(dm)[c(29,30)],
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('employ_rate','Gov_ex','Secondary_ed'),
                              lags_exog_data = 1,
                              l_exog_data    = colnames(dm)[c(23)],
                              l_fd_exog_data    = colnames(dm)[c(12,3)],
                              lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

lpr2 = data.frame(x =1:5,estm=c(pr2[["irf_panel_mean"]]),low=c(pr2[["irf_panel_low"]]),up=c(pr2[["irf_panel_up"]]))

pr3 <-  lp_lin_panel(data_set          = dm,
                              data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "lkind",
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                                 gmm_model = 'twosteps', gmm_effect = 'individual',
                                instrum =   colnames(dm)[c(29,30)],
                                 robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                                 c_exog_data   = c('employ_rate','Gov_ex','Secondary_ed'),
                                lags_exog_data = 1,
                                l_exog_data    = colnames(dm)[c(23)],
                                l_fd_exog_data    = colnames(dm)[c(12,3)],
                                lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

lpr3 = data.frame(x =1:5,estm=c(pr3[["irf_panel_mean"]]),low=c(pr3[["irf_panel_low"]]),up=c(pr3[["irf_panel_up"]]))

pr4 <-  lp_lin_panel(data_set          = dm,
                              data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "lpay",
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                                gmm_model = 'twosteps', gmm_effect = 'individual',
                                instrum =   colnames(dm)[c(29,30)],
                                 robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                                 c_exog_data   = c('employ_rate','Gov_ex','Secondary_ed'),
                                lags_exog_data = 1,
                                l_exog_data    = colnames(dm)[c(23)],
                                l_fd_exog_data    = colnames(dm)[c(12,3)],
                                lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

lpr4 = data.frame(x =1:5,estm=c(pr4[["irf_panel_mean"]]),low=c(pr4[["irf_panel_low"]]),up=c(pr4[["irf_panel_up"]]))

# NO me vale

pr5 <-  lp_lin_panel(data_set          = dm,
                              data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                              shock             = "Unemp_tra",
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                               gmm_model = 'twosteps', gmm_effect = 'individual',
                                instrum =   colnames(dm)[c(29,30,13)],
                                 robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                                 c_exog_data   = c('employ_rate','Gov_ex','Secondary_ed'),
                                lags_exog_data = 1,
                                l_exog_data    = colnames(dm)[c(23)],
                                l_fd_exog_data    = colnames(dm)[c(12,3)],
                                lags_fd_exog_data = 1, confint = 1.96, hor = 5)

lpr5 = data.frame(x =1:5,estm=c(pr5[["irf_panel_mean"]]),low=c(pr5[["irf_panel_low"]]),up=c(pr5[["irf_panel_up"]]))
```

```{r}
cfi <- function(hori, me, low, up, color, tit) {
  plot(hori, me, ylim = c(y2,y1), type = "l", main = tit, xlab = "horizon", ylab= '')
  polygon(c(hori,rev(hori)),c(low,rev(up)), col = adjustcolor("gray70" ,alpha.f=0.3) , border = NA)
  lines(hori, me, lwd = 2, col = color)
  lines(hori, up, lty = 'dashed', col="gray")
  lines(hori, low, lty = 'dashed', col="gray")
}

```

```{r}
## "Education_exp"
y1 = max(lp1$up) + 0.05
y2 = min(lp1$low) - 0.05

par(mfrow=c(1,2))

cfi(lp1$x, lp1$estm,lp1$low,lp1$up, 'blue', 'Normal')

y1 = max(lpr1$up) + 0.05
y2 = min(lpr1$low) - 0.05

cfi(lpr1$x,lpr1$estm,lpr1$low,lpr1$up, 'firebrick', 'Recession')
```

```{r}
## "Health_exp"
y1 = 0.1
y2 = -0.2

par(mfrow=c(1,2))

cfi(lp2$x,lp2$estm,lp2$low,lp2$up, 'blue', 'Normal')

y1 = 0.1
y2 = -0.2 

cfi(lpr2$x,lpr2$estm,lpr2$low,lpr2$up, 'firebrick', 'Recession')
```

```{r}
## "Transfers in Kind"
y1 = max(lp3$up) + 0.05
y2 = min(lp3$low) - 0.05

par(mfrow=c(1,2))

cfi(lp3$x,lp3$estm,lp3$low,lp3$up, 'blue', 'Normal')

y1 = max(lpr3$up) + 0.05
y2 = min(lpr3$low) - 0.05

cfi(lpr3$x,lpr3$estm,lpr3$low,lpr3$up, 'firebrick', 'Recession')
```

```{r}
## "Transfers in Cash"
y1 = max(lp4$up) + 0.05
y2 = min(lp4$low) - 0.05

par(mfrow=c(1,2))

cfi(lp4$x,lp4$estm,lp4$low,lp4$up, 'blue', 'Normal')

y1 = max(lpr4$up) + 0.05
y2 = min(lpr4$low) - 0.05

cfi(lpr4$x,lpr4$estm,lpr4$low,lpr4$up, 'firebrick', 'Recession')
```

```{r}
## Social_prot_ex_pen

y1 = max(lp5$up) + 0.05
y2 = min(lp5$low) - 0.05

par(mfrow=c(1,2))

cfi(lp5$x,lp5$estm,lp5$low,lp5$up, 'blue', 'Normal')

cfi(lpr5$x,lpr5$estm,lpr5$low,lpr5$up, 'firebrick', 'Recession')
```

## TAXES

```{r}
t1 <-  lp_lin_panel(data_set          = dm,
                              # data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "Property_taxes",
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                              gmm_model = 'twosteps', gmm_effect = 'individual',
                              instrum =   colnames(dm)[c(29,30)],
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('employ_rate', 'Gov_ex',"Secondary_ed"),
                              lags_exog_data = 1,
                              l_exog_data    = colnames(dm)[(23)],
                              l_fd_exog_data    = colnames(dm)[c(12,3)],
                              lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

lt1 = data.frame(x =1:5,estm=c(t1[["irf_panel_mean"]]),low=c(t1[["irf_panel_low"]]),up=c(t1[["irf_panel_up"]]))

t2 <-  lp_lin_panel(data_set          = dm,
                              # data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "pi_m",
                               diff_shock        = TRUE,
                                 panel_model       = "within",
                              panel_effect      = "individual",
                               gmm_model = 'twosteps', gmm_effect = 'individual',
                              instrum =   colnames(dm)[c(29,30)],
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('employ_rate', 'Gov_ex',"Secondary_ed"),
                              lags_exog_data = 1,
                              l_exog_data    = colnames(dm)[(23)],
                              l_fd_exog_data    = colnames(dm)[c(12,3)],
                              lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

lt2 = data.frame(x =1:5,estm=c(t2[["irf_panel_mean"]]),low=c(t2[["irf_panel_low"]]),up=c(t2[["irf_panel_up"]]))

t3 <-  lp_lin_panel(data_set          = dm,
                              # data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "ind_tx",
                               diff_shock        = TRUE,
                              panel_model       = "within",
                              panel_effect      = "individual",
                               gmm_model = 'twosteps', gmm_effect = 'individual',
                              instrum =   colnames(dm)[c(29,30)],
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('employ_rate', 'Gov_ex',"Secondary_ed"),
                              lags_exog_data = 1,
                              l_exog_data    = colnames(dm)[(23)],
                              l_fd_exog_data    = colnames(dm)[c(12,3)],
                              lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

lt3 = data.frame(x =1:5,estm=c(t3[["irf_panel_mean"]]),low=c(t3[["irf_panel_low"]]),up=c(t3[["irf_panel_up"]]))

```

```{r}
tr1 <-  lp_lin_panel(data_set          = dm,
                              data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "Property_taxes",
                               diff_shock        = TRUE,
                              panel_model       = "within",
                               panel_effect      = "individual",
                                gmm_model = 'twosteps', gmm_effect = 'individual',
                              instrum =   colnames(dm)[c(29,30)],
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('employ_rate', 'Gov_ex',"Secondary_ed"),
                              lags_exog_data = 1,
                              l_exog_data    = colnames(dm)[(23)],
                              l_fd_exog_data    = colnames(dm)[c(12,3)],
                              lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

ltr1 = data.frame(x =1:5,estm=c(tr1[["irf_panel_mean"]]),low=c(tr1[["irf_panel_low"]]),up=c(tr1[["irf_panel_up"]]))

tr2 <-  lp_lin_panel(data_set          = dm,
                              data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "pi_m",
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                                gmm_model = 'twosteps', gmm_effect = 'individual',
                              instrum =   colnames(dm)[c(29,30)],
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('employ_rate', 'Gov_ex',"Secondary_ed"),
                              lags_exog_data = 1,
                              l_exog_data    = colnames(dm)[(23)],
                              l_fd_exog_data    = colnames(dm)[c(12,3)],
                              lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

ltr2 = data.frame(x =1:5,estm=c(tr2[["irf_panel_mean"]]),low=c(tr2[["irf_panel_low"]]),up=c(tr2[["irf_panel_up"]]))

tr3 <-  lp_lin_panel(data_set          = dm,
                              data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "ind_tx",
                               diff_shock        = TRUE,
                               panel_model       = "within",
                               panel_effect      = "individual",
                                gmm_model = 'twosteps', gmm_effect = 'individual',
                              instrum =   colnames(dm)[c(29,30)],
                               robust_cov   = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data   = c('employ_rate', 'Gov_ex',"Secondary_ed"),
                              lags_exog_data = 1,
                              l_exog_data    = colnames(dm)[(23)],
                              l_fd_exog_data    = colnames(dm)[c(12,3)],
                              lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

ltr3 = data.frame(x =1:5,estm=c(tr3[["irf_panel_mean"]]),low=c(tr3[["irf_panel_low"]]),up=c(tr3[["irf_panel_up"]]))

```

```{r}
## Property_taxes

y1 = max(lt1$up) +0.015
y2 = min(lt1$low) 

par(mfrow=c(1,2))

cfi(lt1$x,lt1$estm,lt1$low,lt1$up, 'blue', 'Normal')

cfi(ltr1$x,ltr1$estm,ltr1$low,ltr1$up, 'firebrick', 'Recession')
```

```{r}
## PIT

y1 = max(lt2$up) + 0.05
y2 = min(lt2$low) 

par(mfrow=c(1,2))

cfi(lt2$x,lt2$estm,lt2$low,lt2$up, 'blue', 'Normal')

cfi(ltr2$x,ltr2$estm,ltr2$low,ltr2$up, 'firebrick', 'Recession')
```

```{r}
## ind_tx

y1 = max(lt3$up) + 0.05
y2 = min(lt3$low) - 0.05

par(mfrow=c(1,2))

cfi(lt3$x,lt3$estm,lt3$low,lt3$up, 'blue', 'Normal')

cfi(ltr3$x,ltr3$estm,ltr3$low,ltr3$up, 'firebrick', 'Recession')
```

## R&D ESTO ES CORRECTO

```{r}
d1 <-  lp_lin_panel(data_set          = dm,
                              # data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "RD_gdp",
                               diff_shock        = TRUE,
                                panel_model       = "within",
                               panel_effect      = "individual",
                               gmm_model = 'twosteps', gmm_effect = 'individual',
                              instrum =        colnames(dm)[c(29,30)],
                               robust_cov        = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data       = c('employ_rate', 'Gov_ex',"Secondary_ed"),
                             lags_exog_data = 1,
                              l_exog_data    = colnames(dm)[(23)],
                               l_fd_exog_data    = colnames(dm)[c(12,3)],
                               lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

ld1 = data.frame(x =1:5,estm=c(d1[["irf_panel_mean"]]),low=c(d1[["irf_panel_low"]]),up=c(d1[["irf_panel_up"]]))

# Este modelo no me gusta, no tomar en el ejemplo

d2 <-  lp_lin_panel(data_set          = dm,
                              # data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "sav_gdp",
                               diff_shock        = TRUE,
                                 panel_model       = "within",
                               panel_effect      = "individual",
                              instrum =        colnames(dm)[c(29,30)],
                               robust_cov        = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data       = c('employ_rate', 'Gov_ex',"Secondary_ed"),
                             lags_exog_data = 1,
                              l_exog_data    = colnames(dm)[c(23)],
                               l_fd_exog_data    = colnames(dm)[c(12,3)],
                               lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

ld2 = data.frame(x =1:5,estm=c(d2[["irf_panel_mean"]]),low=c(d2[["irf_panel_low"]]),up=c(d2[["irf_panel_up"]]))

# No me convence, es la interaccion del modelo entre RD y SAV

d3 <-  lp_lin_panel(data_set          = dm,
                              # data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "rd1",
                               diff_shock        = TRUE,
                                 panel_model       = "within",
                               panel_effect      = "individual",
                              instrum =        colnames(dm)[c(29,30)],
                           robust_cov        = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data       = c('employ_rate', 'Gov_ex',"Secondary_ed"),
                             lags_exog_data = 1,
                              l_exog_data    = colnames(dm)[c(23)],
                               l_fd_exog_data    = colnames(dm)[c(12,3)],
                               lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

ld3 = data.frame(x =1:5,estm=c(d3[["irf_panel_mean"]]),low=c(d3[["irf_panel_low"]]),up=c(d3[["irf_panel_up"]]))
```

## RECESSION

```{r}
dr1 <-  lp_lin_panel(data_set          = dm,
                              data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "RD_gdp",
                               diff_shock        = TRUE,
                            panel_model       = "within",
                                  panel_effect =   "individual",
                                   gmm_model = 'twosteps', gmm_effect = 'individual',
                              instrum =        colnames(dm)[c(29,30)],
                                robust_cov        = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data       = c('employ_rate', 'Gov_ex',"Secondary_ed"),
                             lags_exog_data = 1,
                              l_exog_data    = colnames(dm)[(23)],
                               l_fd_exog_data    = colnames(dm)[c(12,3)],
                               lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

ldr1 = data.frame(x =1:5,estm=c(dr1[["irf_panel_mean"]]),low=c(dr1[["irf_panel_low"]]),up=c(dr1[["irf_panel_up"]]))

dr2 <-  lp_lin_panel(data_set          = dm,
                              data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "sav_gdp",
                               diff_shock        = TRUE,
                                  panel_model       = "within",
                               panel_effect      = "individual",
                              instrum =        colnames(dm)[c(29,30)],
                              robust_cov        = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data       = c('employ_rate', 'Gov_ex',"Secondary_ed"),
                             lags_exog_data = 1,
                              l_exog_data    = colnames(dm)[(23)],
                               l_fd_exog_data    = colnames(dm)[c(12,3)],
                               lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

ldr2 = data.frame(x =1:5,estm=c(dr2[["irf_panel_mean"]]),low=c(dr2[["irf_panel_low"]]),up=c(dr2[["irf_panel_up"]]))

dr3 <-  lp_lin_panel(data_set          = dm,
                              data_sample       = data_sample,
                               endog_data        = c("Gini_net"),
                               cumul_mult        = TRUE,
                               shock             = "rd1",
                               diff_shock        = TRUE,
                                  panel_model       = "within",
                               panel_effect      = "individual",
                              instrum =        colnames(dm)[c(29,30)],
                               robust_cov        = "vcovSCC", robust_type="HC0", robust_cluster= "vcovHC",
                               c_exog_data       = c('employ_rate', 'Gov_ex',"Secondary_ed"),
                             lags_exog_data = 1,
                              l_exog_data    = colnames(dm)[(23)],
                               l_fd_exog_data    = colnames(dm)[c(12,3)],
                               lags_fd_exog_data = 1,  confint  = 1.96, hor = 5)

ldr3 = data.frame(x =1:5,estm=c(dr3[["irf_panel_mean"]]),low=c(dr3[["irf_panel_low"]]),up=c(dr3[["irf_panel_up"]]))
```

```{r}
## R&D

y1 = max(ld1$up) + 0.05
y2 = min(ld1$low) - 0.05

par(mfrow=c(1,2))

cfi(ld1$x,ld1$estm,ld1$low,ld1$up, 'blue', 'Normal')

cfi(ldr1$x,ldr1$estm,ldr1$low,ldr1$up, 'firebrick', 'Recession')
```

```{r}
## Savings

y1 = max(ld2$up) + 0.05
y2 = min(ld2$low) - 0.05

par(mfrow=c(1,2))

cfi(ld2$x,ld2$estm,ld2$low,ld2$up, 'blue', 'Normal')

cfi(ldr2$x,ldr2$estm,ldr2$low,ldr2$up, 'firebrick', 'Recession')
```

```{r}

y1 = max(ld3$up) + 0.05
y2 = min(ld3$low) - 0.05

par(mfrow=c(1,2))

cfi(ld3$x,ld3$estm,ld3$low,ld3$up, 'blue', 'Normal')

cfi(ldr3$x,ldr3$estm,ldr3$low,ldr3$up, 'firebrick', 'Recession')
```

```{r}
library(clipr)

mat.1 <- matrix( 1:9, nrow=3, dimnames=list( rows=letters[1:3], columns=letters[24:26]))

write_clip(mat.1)
mat2 <-read_clip_tbl()

```
