---
title: "Base sample"
output:
  html_document:
    df_print: paged
---


```{r, message=FALSE}
library(readxl)

final <- read_excel("final.xlsx")
```


```{r,message=FALSE}
library(plm)
library(tidyverse)
library(lfe)
library(lmtest)
library(texreg)
```

```{r}
final <- final %>%
  arrange(idem, year) %>%  # Sort by firm and then by year
  group_by(idem) %>%      # Tell dplyr to go within each firm
  mutate(gdppc_gro = GDP_pc/(lag(GDP_pc)-1),
         gdp_gro = GDP/(lag(GDP)-1),
         insde_d = ins_effic/(lag(ins_effic)-1),
         tot_d = TOT/(lag(TOT)-1), 
         debt_d = Gov_debt/(lag(Gov_debt)-1),
         redis = Gini_market - Gini_net/Gini_net)


panel.plm.df <- pdata.frame(final, index=c("idem","year"), drop.index=TRUE)

attach(panel.plm.df)
```

Resultados de un modelo con fixed effects y pooling

```{r}
fe_lm <- plm(Gini_net ~ lag(gdp_gro, 1) + Unempl_rate + Trade + Gov_ex + Secondary_ed ,
                        data = panel.plm.df, 
                        index=c("idem", "year"), model="within", effect = c("individual"))
summary(fe_lm)

yhat <- fe_lm$fitted
plot(final$gdp_gro, final$Gini_net, pch=19, xlab="GDP growth", ylab="Gini_net")
abline(lm(final$Gini_net~final$gdp_gro),lwd=3, col="red")

pl_lm <- plm(Gini_net ~ lag(GDP_pc) + lag(Gini_market) + Trade + instdepth + Gov_ex + Secondary_ed ,
                        data = panel.plm.df, 
                        index=c("idem", "year"), model="pooling", effect = c("individual"))

summary(pl_lm)
```

```{r}
library(gplots)
plotmeans(Gini_net ~ idem, main="Heterogeineity across countries", data=final, bars=T, lwd=2)

# Mejorar por 3 grupos
```


```{r}
pFtest(fe_lm, pl_lm)

# In both cases the null hypothesis is rejected in favor of the alternative that there are significant fixed effects.

```

```{r}
wi_lm <- plm(Gini_net ~ (gdp_gro) + employ_rate +Trade +  Gov_ex + Secondary_ed ,  data = panel.plm.df, 
   index=c("idem", "year"), model="within", effect = c("twoways"))

summary(wi_lm)

pFtest(fe_lm, wi_lm) 

# There is evidence that time fixed effects should be taken into account.
```

```{r, eval=FALSE}
ra_lm <- plm(Gini_net ~ lag(GDP_pc) + lag(Gini_market) + Trade + instdepth + Gov_ex + Secondary_ed ,
                        data = panel.plm.df, 
                        index=c("idem", "year"), model="random", effect = c("individual"))

summary(ra_lm)
summary(fe_lm)

phtest(fe_lm, ra_lm)

# The null hypothesis cannot be rejected here, hence we should use a FE model.
```

```{r}
lmtest::bptest(Gini_net ~ lag(GDP_pc) + lag(Gini_market) + Trade + instdepth + Gov_ex + Secondary_ed + factor(idem), studentize = F, data = final)

# here is strong evidence for the presense of heteroskedasticity. Hence, the use of robust standard errors is advised.

pbgtest(fe_lm)

# There is strong evidence that the residuals are serially correlated.
```

```{r}
fe_s =coeftest(fe_lm, vcov = (vcovHC(fe_lm, method='arellano',type = "HC1",cluster = "group")))

fe_s
# summary(fe_lm)

# fe_s2 <- lfe::felm(Gini_net ~ lag(GDP_pc) + lag(Gini_market) + Trade + instdepth + Gov_ex + Secondary_ed | idem | 0 | idem, data = final)
# 
# summary(fe_s2)

wi_s =coeftest(wi_lm, vcov = (vcovHC(wi_lm, method='arellano',type = "HC2",cluster = "group")))

wi_s

# ercomp(Gini_net ~ lag(GDP_pc) + lag(Gini_market) + Trade + instdepth + Gov_ex + Secondary_ed, data=final, 
       # method = "nerlove", effect = "twoways")

```

De los resultados anteriores solucionando los problemas de autocorrelación y heteroscedasticidad, vemos que controlando el modelo por tiempo y fixed effects es mejor que sólo con FE.


```{r}
ftime <- plm(Gini_net ~ lag(GDP_pc) + lag(Gini_market) + Trade  + Gov_ex + Secondary_ed  + factor(year),    data = final, index=c("idem","year"), model="within")

summary(ftime)

pFtest(wi_lm, fe_lm)
plmtest(fe_lm, c("time"), type=("bp"))

# If this number is < 0.05 then use time-fixed effects. In this example, no need to use
# time-fixed effects.
```

```{r}
# Testing for cross-sectional dependence

# Evidence of CS dependence and Correlation

pcdtest(fe_lm, test = c("lm"))
pcdtest(fe_lm, test = c("cd"))

pbgtest(fe_lm)

# Presence of heteroskedasticity
bptest(Gini_net ~ lag(GDP_pc) + lag(Gini_market) + Trade + instdepth + Gov_ex + Secondary_ed  + factor(idem), data = final, studentize=F)

coeftest(fe_lm)

fe_so1 <- coeftest(fe_lm, vcovHC(fe_lm, method = "arellano",  type = "HC3"))
fe_so2 <- coeftest(fe_lm, vcovHC(fe_lm, cluster = "group",  type = "HC3"))

wi_so1 <- coeftest(wi_lm, vcovHC(wi_lm, method = "arellano",  type = "HC3"))
wi_so2 <- coeftest(wi_lm, vcovHC(wi_lm, type = "HC3", cluster = "group"))

screenreg(list(fe_so1, fe_so2, wi_so2),
          custom.model.names = c("FE_au", "FE_cd", "Two"))

wi_so2[,1] / diff(range(final$Gini_net, na.rm = TRUE))
```

## Adding external variables

## leer para estimacion final
https://cran.r-project.org/web/packages/plm/vignettes/A_plmPackage.html


```{r}
fe_1 <- plm(Gini_net ~ (gdp_gro) + Unempl_rate + Trade + Gov_ex + Secondary_ed +
                Soc_payable,
                        data = panel.plm.df, 
                        index=c("idem", "year"), model="within", effect = c("individual"))
fe_2 <- plm(Gini_net ~ (gdp_gro) + Unempl_rate + Trade + Gov_ex + Secondary_ed +
                Soc_kind,
                        data = panel.plm.df, 
                        index=c("idem", "year"), model="within", effect = c("individual"))
fe_3 <- plm(Gini_net ~ (gdp_gro) + Unempl_rate +Trade +  Gov_ex + Education_exp,  data = panel.plm.df, 
   index=c("idem", "year"), model="within", effect = c("individual"))
fe_4 <- plm(Gini_net ~ (gdp_gro) + Unempl_rate +Trade +  Gov_ex + Secondary_ed + Health_exp,  data = panel.plm.df, index=c("idem", "year"), model="within", effect = c("individual"))
fe_5 <- plm(Gini_net ~ (gdp_gro) + Unempl_rate +Trade +  Gov_ex + Secondary_ed + Social_prot,  data = panel.plm.df,  index=c("idem", "year"), model="within", effect = c("individual"))
fe_6 <- plm(Gini_net ~ (gdp_gro) + Unempl_rate +Trade +  Gov_ex + Secondary_ed + Family,  data = panel.plm.df, 
   index=c("idem", "year"), model="within", effect = c("individual"))

## DIRECT POLICY VARIABLES
wi_1 <- plm(Gini_net ~ lag(gdp_gro) + employ_rate +Trade +  Gov_ex + Secondary_ed +  + Soc_payable,  data = panel.plm.df, index=c("idem", "year"), model="within", effect = c("twoways"))
wi_2 <- plm(Gini_net ~ lag(gdp_gro) + employ_rate +Trade +  Gov_ex + Secondary_ed + + Soc_kind,  data = panel.plm.df, index=c("idem", "year"), model="within", effect = c("twoways"))
wi_3 <- plm(Gini_net ~ lag(gdp_gro) + employ_rate +Trade +  Gov_ex +  + Education_exp,  data = panel.plm.df,  index=c("idem", "year"), model="within", effect = c("twoways"))
wi_4 <- plm(Gini_net ~ lag(gdp_gro) + employ_rate +Trade +  Gov_ex + Secondary_ed +  + Health_exp,  data = panel.plm.df, index=c("idem", "year"), model="within", effect = c("twoways"))
wi_5 <- plm(Gini_net ~ lag(gdp_gro) + employ_rate +Trade +  Gov_ex + Secondary_ed +  + Social_prot,  data = panel.plm.df,  index=c("idem", "year"), model="within", effect = c("twoways"))
wi_6 <- plm(Gini_net ~ lag(gdp_gro) + employ_rate +Trade +  Gov_ex + Secondary_ed +  + Family,  data = panel.plm.df, index=c("idem", "year"), model="within", effect = c("twoways"))

# PUBLIC REVENUES VAR.
### DIRECT TAXATION
wi_7 <- plm(Gini_net ~ lag(gdp_gro) +employ_rate +Trade +  Gov_ex + Secondary_ed + property_tx*arp_mid,  data = panel.plm.df,  index=c("idem", "year"), model="within", effect = c("twoways"))
wi_8 <- plm(Gini_net ~ lag(gdp_gro) +employ_rate +Trade +  Gov_ex + Secondary_ed + arp_mid*PIT, data = panel.plm.df,  index=c("idem", "year"), model="within", effect = c("twoways"))
wi_9 <- plm(Gini_net ~ lag(gdp_gro) +employ_rate +Trade +  Gov_ex + Secondary_ed + mrp_all*PIT, data = panel.plm.df,  index=c("idem", "year"), model="within", effect = c("twoways"))
wi_10 <- plm(Gini_net ~ lag(gdp_gro) +employ_rate +Trade +  Gov_ex + Secondary_ed + Corporate_ta, data = panel.plm.df,  index=c("idem", "year"), model="within", effect = c("twoways"))
### INDIRECT TAXATION
wi_11 <- plm(Gini_net ~ lag(gdp_gro) +employ_rate +Trade +  Gov_ex + Secondary_ed + VAT, data = panel.plm.df,  index=c("idem", "year"), model="within", effect = c("twoways"))
wi_12 <- plm(Gini_net ~ lag(gdp_gro) +employ_rate +Trade +  Gov_ex + Secondary_ed + ind_tx, data = panel.plm.df,  index=c("idem", "year"), model="within", effect = c("twoways"))
wi_13 <- plm(Gini_net ~ lag(gdp_gro) +employ_rate +Trade +  Gov_ex + Secondary_ed + trade, data = panel.plm.df,  index=c("idem", "year"), model="within", effect = c("twoways"))
wi_14 <- plm(Gini_net ~ lag(gdp_gro) +employ_rate +Trade +  Gov_ex + Secondary_ed + pro_imp_tx, data = panel.plm.df,  index=c("idem", "year"), model="within", effect = c("twoways"))

fe_ex1 <- coeftest(fe_1, vcovHC(fe_1, method = "arellano", cluster = 'group',type = "HC3"))
fe_ex2 <- coeftest(fe_2, vcovHC(fe_2, method  = "arellano", cluster = 'group', type = "HC3"))
fe_ex3 <- coeftest(fe_3, vcovHC(fe_3, method = "arellano", cluster = 'group',type = "HC3"))
fe_ex4 <- coeftest(fe_4, vcovHC(fe_4, method  = "arellano", cluster = 'group', type = "HC3"))
fe_ex5 <- coeftest(fe_5, vcovHC(fe_5, method = "arellano", cluster = 'group',type = "HC3"))
fe_ex6 <- coeftest(fe_6, vcovHC(fe_6, method  = "arellano", cluster = 'group', type = "HC3"))


wi_ex1 <- coeftest(wi_1, vcovHC(wi_1, method = "arellano",  cluster = 'time', type = "HC3"))
wi_ex2 <- coeftest(wi_2, vcovHC(wi_2, type = "HC3", cluster = 'time', method  = "arellano"))
wi_ex3 <- coeftest(wi_3, vcovHC(wi_3, method = "arellano",  cluster = 'time', type = "HC3"))
wi_ex4 <- coeftest(wi_4, vcovHC(wi_4, type = "HC3", cluster = 'time', method  = "arellano"))
wi_ex5 <- coeftest(wi_5, vcovHC(wi_5, method = "arellano",  cluster = 'time', type = "HC3"))
wi_ex6 <- coeftest(wi_6, vcovHC(wi_6, type = "HC3", cluster = 'time', method  = "arellano"))

wi_ex7 <- coeftest(wi_7, vcovHC(wi_7, type = "HC3", cluster = 'time', method  = "arellano"))
wi_ex8 <- coeftest(wi_8, vcovHC(wi_8, method = "arellano",  cluster = 'time', type = "HC3"))
wi_ex9 <- coeftest(wi_9, vcovHC(wi_9, type = "HC3", cluster = 'time', method  = "arellano"))

wi_ex10 <- coeftest(wi_10, vcovHC(wi_10, type = "HC3", cluster = 'time', method  = "arellano"))
wi_ex11 <- coeftest(wi_11, vcovHC(wi_11, type = "HC3", cluster = 'time', method  = "arellano"))
wi_ex12 <- coeftest(wi_12, vcovHC(wi_12, type = "HC3", cluster = 'time', method  = "arellano"))
wi_ex13 <- coeftest(wi_13, vcovHC(wi_13, type = "HC3", cluster = 'time', method  = "arellano"))

screenreg(list(fe_ex1, fe_ex2,fe_ex3, fe_ex4,fe_ex5, fe_ex6),
          custom.model.names = c("FE_1", "FE_2", "FE_3", "FE_4","FE_5","FE_6"))

ta1 = screenreg(list(wi_ex1, wi_ex2, wi_ex3, wi_ex4, wi_ex5, wi_ex6),
          custom.model.names = c("TE_1","TE_2","TE_3","TE_4","TE_5","TE_6"))
ta1

# PUBLIC REVENUES
tpb = screenreg(list(wi_ex7,wi_ex8,wi_ex9, wi_ex10, wi_ex11, wi_ex12, wi_ex13),
          custom.model.names = c("TE_7","TE_8","TE_9","TE_10","TE_11","TE_12","TE_13"))
tpb

# Analizando resultados (obteniendo parámetros)
wi_ex1[,1] / diff(range(final$Gini_net, na.rm = T))
```

```{r}
"GDP_pc", "employ_rate", "Trade",'Gov_ex', "Education_exp"
## DIRECT POLICY VARIABLES
library(pacman)
library(panelvar)

data <- fn %>% drop_na()
fn <- as.data.frame(final %>% select("GDP_pc", "employ_rate", "Trade",'Gov_ex', "Education_exp",'idem','year'))
final <- as.data.frame(final)

wl_1 <- pvargmm(dependent_vars = c("Gini_net","Education_exp"), predet_vars = c("gdp_gro",'Gov_ex', "Trade"),  lags = 1, exog_vars = c("employ_rate", 'Secondary_ed'), max_instr_predet_vars = 4, 
  transformation = "fd",  data =final, panel_identifier = c('idem','year'),
  steps = c("onestep"),  system_instruments = FALSE, max_instr_dependent_vars =4,  
  min_instr_dependent_vars = 1L,  collapse = FALSE)

summary(wl_1)

wl_stab = stability(wl_1)
plot(wl_stab)
fo_w1 <- oirf(wl_1, n.ahead = 5)
gi_w1 <- girf(wl_1, n.ahead = 5, ma_approx_steps= 5)    
 

wl1_bs <-  bootstrap_irf(wl_1,  typeof_irf = c("GIRF"),
    n.ahead = 5,nof_Nstar_draws = 10, confidence.band = 0.95)

plot(gi_w1,wl1_bs)
    
Andrews_Lu_MMSC(wl_1)

wl_1 <- plm(Gini_net ~ lag(gdp_gro) + lag(Gini_net,2) + employ_rate +Trade +  Gov_ex + Secondary_ed +  + Soc_payable,  data = panel.plm.df, index=c("idem", "year"), model="within", effect = c("twoways"))
wl_2 <- plm(Gini_net ~ lag(gdp_gro)+ lag(Gini_net,2) + employ_rate +Trade +  Gov_ex + Secondary_ed + + Soc_kind,  data = panel.plm.df, index=c("idem", "year"), model="within", effect = c("twoways"))
wl_3 <- plm(Gini_net ~ lag(gdp_gro) + lag(Gini_net,2)+ employ_rate +Trade +  Gov_ex + Secondary_ed + Education_exp,  data = panel.plm.df,  index=c("idem", "year"), model="within", effect = c("twoways"))
wl_4 <- plm(Gini_net ~ lag(gdp_gro) + lag(Gini_net,2)+ employ_rate +Trade +  Gov_ex + Secondary_ed +  + Health_exp,  data = panel.plm.df, index=c("idem", "year"), model="within", effect = c("twoways"))
wl_5 <- plm(Gini_net ~ lag(gdp_gro) + lag(Gini_net,2)+ employ_rate +Trade +  Gov_ex + Secondary_ed +  + Social_prot,  data = panel.plm.df,  index=c("idem", "year"), model="within", effect = c("twoways"))
wl_6 <- plm(Gini_net ~ lag(gdp_gro) + lag(Gini_net,2)+ employ_rate +Trade +  Gov_ex + Secondary_ed +  + Family,  data = panel.plm.df, index=c("idem", "year"), model="within", effect = c("twoways"))


wl_ex1 <- coeftest(wl_1, vcovHC(wl_1, method = "arellano",  cluster = 'time', type = "HC3"))
wl_ex2 <- coeftest(wl_2, vcovHC(wl_2, type = "HC3", cluster = 'time', method  = "arellano"))
wl_ex3 <- coeftest(wl_3, vcovHC(wl_3, method = "arellano",  cluster = 'time', type = "HC3"))
wl_ex4 <- coeftest(wl_4, vcovHC(wl_4, type = "HC3", cluster = 'time', method  = "arellano"))
wl_ex5 <- coeftest(wl_5, vcovHC(wl_5, method = "arellano",  cluster = 'time', type = "HC3"))
wl_ex6 <- coeftest(wl_6, vcovHC(wl_6, type = "HC3", cluster = 'time', method  = "arellano"))

tl1 = screenreg(list(wl_ex1, wl_ex2, wl_ex3, wl_ex4, wl_ex5, wl_ex6),
          custom.model.names = c("TE_1","TE_2","TE_3","TE_4","TE_5","TE_6"))
tl1

```


##  ASSESING TECH

```{r}
wi_rd <- plm(Gini_net ~ (gdp_gro) + employ_rate +Trade +  Gov_ex + Secondary_ed +  res_1mill,  data = panel.plm.df,  index=c("idem", "year"), model="within", effect = c("twoways"))

wi_rd1 <- plm(Gini_net ~ (gdp_gro) + employ_rate +Trade +  Gov_ex + Secondary_ed + res_1mill*pro_imp_tx,  data = panel.plm.df,  index=c("idem", "year"), model="within", effect = c("twoways"))

summary(wi_rd1)

plot(final$PIT, final$Gini_net)
abline(lm(final$Gini_net~final$PIT), col="red") # regression line (y~x)

plot(final$pro_imp_tx, final$Gini_net)
abline(lm(final$Gini_net~final$pro_imp_tx), col="blue")

library("car")
scatterplot(final$Gini_net ~ final$pro_imp_tx | debt_g, data = final, smooth=T, col=c('blue','orange'))

scatterplot(final$Gini_net ~ final$PIT | debt_g, data = final, smooth=F, col=c('blue','orange'))

scatterplot(final$Gini_net ~ final$PIT, data = final, smooth=list(smoother=quantregLine, var=T, span=1, lwd=4, lwd.var=2, border=F),regLine=F)
```


##  ASSESING SAVINGS + TECH

```{r}
wi_sv <- plm(Gini_net ~ gdp_gro + employ_rate +Trade + Gov_ex + Secondary_ed + Savings_percapit*res_1mill,  data = panel.plm.df, index=c("idem", "year"), model="within", effect = c("twoways"))
summary(wi_sv)

plot(final$Savings_percapit, final$Gini_net)
abline(lm(final$Gini_net~final$Savings_percapit), col="red") # regression line (y~x)

plot(final$pro_imp_tx, final$Gini_net)
abline(lm(final$Gini_net~final$pro_imp_tx), col="blue")

library("car")
scatterplot(final$Gini_net ~ final$pro_imp_tx | debt_g, data = final, smooth=T, col=c('blue','orange'))

scatterplot(final$res_1mill ~ final$Savings_percapit | debt_g, data = final, smooth=T, col=c('blue','orange'))

scatter3d(x = final$Savings_percapit, y = final$Gini_net, z = final$res_1mill, point.col = "blue", surface=FALSE)

LETTER2num <- function(x) {utf8ToInt(x) - utf8ToInt("A") + 1L}

colors <- unname(sapply(final$debt_g, LETTER2num))

sd <- scatterplot3d(x = Savings_percapit, z = Gini_net, y = res_1mill, color=colors,pch = 16)
legend('bottomright', legend = levels(lev), col =  c("1", "2"), pch = 15, xpd = TRUE, horiz = TRUE, inset = 0.025)

my.lm <- lm(final$Gini_net ~ final$Savings_percapit + final$res_1mill )
sd$plane3d(my.lm, col='blue')

lev = factor(final$debt_g, levels= c("A", "B"))
```


